// Storefront taxonomy plus the seed catalog that populates the database on first run.
export type SeedColor = { name: string; hex: string; images: string[]; stock: number };
export type SeedProduct = {
  id: string; name: string; subtitle: string; description: string; price: number; category: string;
  capacity?: string; badge?: string; features: string[]; dimensions: string; tags: string[]; colors: SeedColor[];
};
const stockLevels = [26, 9, 4, 17, 0];
function colors(product: string, list: [string, string][]): SeedColor[] {
  return list.map(([name, hex], index) => { const key = name.toLowerCase().replaceAll(' ', '-'); return { name, hex, stock: stockLevels[index % stockLevels.length], images: [`/images/${product}-${key}.jpg`, `/images/${product}-${key}-detail.jpg`] }; });
}
export const seedProducts: SeedProduct[] = [
  { id: 'lite-travel-pack', name: 'Lite Travel Pack', subtitle: 'Light on your back. Big on adventure.', description: 'A lightweight travel backpack with serious organization. The full-opening design makes packing easy, while comfortable straps and thoughtful pockets keep every part of your journey flowing.', price: 199, category: 'backpacks', capacity: '30L', badge: 'BESTSELLER', features: ['Full clamshell opening for easy packing', 'Padded 16-inch laptop sleeve', 'Quick-access pockets for travel essentials', 'Tuck-away shoulder straps', 'Lightweight, durable recycled fabric'], dimensions: '510 × 350 × 210 mm', tags: ['bestsellers', 'lite', 'travel', 'new-releases'], colors: colors('lite-travel-pack', [['Ash', '#c3c9bd'], ['Black', '#323b34']]) },
  { id: 'transit-workpack', name: 'Transit Workpack', subtitle: 'A streamlined backpack for work and life', description: 'From morning commute to after-work adventure, this thoughtfully organized backpack keeps your work tools and daily essentials in their place. A clean look on the outside. A clever place for everything inside.', price: 199, category: 'backpacks', capacity: '20L', badge: 'BESTSELLER', features: ['Separate, easy-access 16-inch laptop compartment', 'Full-zip clamshell opening for easy packing', 'Internal water bottle pocket', 'Contoured, breathable back panel', 'Made with recycled, water-resistant fabric'], dimensions: '500 × 320 × 180 mm', tags: ['bestsellers', 'work', 'transit', 'travel'], colors: colors('transit-workpack', [['Bronze', '#83724f'], ['Black', '#313432'], ['Nightsky', '#354659'], ['Olive', '#707658'], ['Stone', '#b9bbae']]) },
  { id: 'lite-sling', name: 'Lite Sling', subtitle: 'Keep your everyday adventure light', description: 'Designed for freedom of movement. This lightweight sling keeps your essentials organized and ready to go, without weighing down your day.', price: 89, category: 'crossbody-bags', capacity: '7L', badge: 'NEW COLORS', features: ['Lightweight recycled fabric', 'Expandable gusset grows with your day', 'Front zip compartment for quick access', 'Internal organization for small essentials', 'Adjustable strap with magnetic clasp'], dimensions: '320 × 180 × 120 mm', tags: ['bestsellers', 'lite', 'travel', 'outdoor', 'new-releases'], colors: colors('lite-sling', [['Clay', '#ab786b'], ['Black', '#323b34'], ['Ash', '#bec4b9']]) },
  { id: 'tech-kit', name: 'Tech Kit', subtitle: 'All your tech, beautifully organized', description: 'Organize your tech accessories without tangles. This generously sized kit opens flat, so you can find exactly what you need without rummaging.', price: 65, category: 'accessories', badge: 'FAN FAVORITE', features: ['Fits a charging brick, cables, mouse and more', 'Magnetic slip pocket for a power bank', 'Stretch mesh pockets for small essentials', 'Elastic cable organizers', 'Zips open flat for full visibility'], dimensions: '230 × 130 × 72 mm', tags: ['bestsellers', 'tech', 'work', 'travel'], colors: colors('tech-kit', [['Navy', '#344b60'], ['Black', '#353735'], ['Saltbush', '#b7b4a3'], ['Everglade', '#426357']]) },
  { id: 'hide-and-seek', name: 'Hide & Seek', subtitle: 'A classic look with a clever twist', description: 'A slim leather wallet with traditional appeal and progressive features. Keep frequently used cards up front, with a discreet section for extra bills and cards you want to keep out of sight.', price: 89, category: 'wallets', badge: 'BESTSELLER', features: ['Holds 5–12 cards and flat bills', 'RFID protection for peace of mind', 'Hidden coin pouch and bill section', 'Premium, responsibly sourced leather', 'Backed by our 3-year warranty'], dimensions: '115 × 85 mm', tags: ['bestsellers', 'travel', 'classic'], colors: colors('hide-and-seek', [['Caramel', '#ba854f'], ['Black', '#363734'], ['Navy', '#354459'], ['Java', '#685145']]) },
  { id: 'venture-sling', name: 'Venture Sling', subtitle: 'Big adventure. Small footprint.', description: 'A generously sized sling built for full days out. The wide-opening zipper lets you see and reach everything, while clever organization keeps the small stuff sorted.', price: 129, category: 'crossbody-bags', capacity: '6L', badge: 'BESTSELLER', features: ['Expandable gusset grows with your day', 'Wide, easy-access opening', 'Soft-lined sunglasses pocket', 'Adjustable strap with quick-release buckle', 'Water-resistant recycled woven fabric'], dimensions: '300 × 170 × 100 mm', tags: ['bestsellers', 'venture', 'travel', 'outdoor'], colors: colors('venture-sling', [['Fog', '#b3b8b0'], ['Black', '#303632'], ['Deep Ocean', '#3b5d62'], ['Safari', '#b7a073']]) },
  { id: 'transit-carry-on', name: 'Transit Carry-On', subtitle: 'Less luggage. More possibility.', description: 'Go from departure to discovery with carry-on luggage designed around the way you actually travel. Easy access, considered organization and a smooth ride, wherever you land.', price: 349, category: 'luggage', capacity: '40L', badge: 'NEW', features: ['Fits most international carry-on size restrictions', 'Quiet, smooth-rolling wheels', 'Integrated TSA-compatible lock', 'Internal compression system', 'Lightweight, durable construction'], dimensions: '550 × 350 × 230 mm', tags: ['new-releases', 'travel', 'transit', 'bestsellers'], colors: colors('transit-carry-on', [['Black', '#353735'], ['Bronze', '#877d65'], ['Chalk', '#d5d1c4']]) },
  { id: 'venture-ready-pack', name: 'Venture Ready Pack', subtitle: 'Ready for wherever the day takes you', description: 'Work mode, adventure mode, and every mode in between. This versatile all-rounder brings intuitive organization and all-day comfort to the things you love doing.', price: 259, category: 'backpacks', capacity: '26L', badge: 'READY FOR ADVENTURE', features: ['Padded 16-inch laptop sleeve', 'Full-length zip for easy access', 'Quick-access top pocket with internal organization', 'External water bottle pocket', 'Padded breathable back panel and harness'], dimensions: '550 × 350 × 200 mm', tags: ['venture', 'outdoor', 'travel', 'bestsellers'], colors: [{ name: 'Black', hex: '#353736', stock: 14, images: ['/images/venture-ready-pack.jpg', '/images/venture-ready-pack-detail.jpg'] }] },
  { id: 'classic-backpack', name: 'Classic Backpack', subtitle: 'Your everyday, upgraded', description: 'A dependable companion for your everyday adventures, with just the right amount of organization and an understated style that looks at home anywhere.', price: 149, category: 'backpacks', capacity: '20L', features: ['Padded laptop pocket for devices up to 16 inches', 'Quick-access valuables pocket', 'Internal mesh zip pocket', 'Comfortable padded back and shoulder straps', 'Durable, water-resistant recycled fabric'], dimensions: '450 × 320 × 180 mm', tags: ['classic', 'work', 'campus'], colors: colors('classic-backpack', [['Black', '#343634'], ['Camel', '#b79a77'], ['Indigo', '#546677'], ['Olive', '#73755b']]) },
  { id: 'tokyo-totepack', name: 'Tokyo Totepack', subtitle: 'A tote. A backpack. Your choice.', description: 'Made for the urban journey, this versatile bag gives you two ways to carry. Tuck away the backpack straps, grab the handles, and switch things up without slowing down.', price: 189, category: 'tote-bags', capacity: '20L', features: ['Padded 15-inch laptop sleeve', 'Tuck-away backpack straps', 'Vertical front pockets for quick access', 'Pop pockets for a water bottle or umbrella', 'Soft, durable webbing handles'], dimensions: '470 × 370 × 140 mm', tags: ['tokyo', 'work', 'campus'], colors: colors('tokyo-totepack', [['Navy', '#35475b'], ['Bronze', '#8b7c61'], ['Everglade', '#426357']]) },
  { id: 'note-sleeve', name: 'Note Sleeve', subtitle: 'Small in size. Big on possibility.', description: 'The wallet that started a slimmer revolution. Fit your cards, cash and coins in a trim profile, with clever pull-tab access to the cards you use less often.', price: 89, category: 'wallets', features: ['Holds 4–11 cards and flat bills', 'RFID protection', '3 quick-access card slots', 'Pull-tab section for extra cards', 'Premium, responsibly sourced leather'], dimensions: '102 × 90 mm', tags: ['bestsellers', 'classic', 'travel'], colors: colors('note-sleeve', [['Black', '#343632'], ['Java', '#6a4d3c'], ['Everglade', '#436b56']]) },
  { id: 'classic-messenger', name: 'Classic Messenger', subtitle: 'A modern take on a timeless carry', description: 'An easy-going messenger with clever internal organization and a comfortable fit. Keep your laptop, work gear and daily essentials moving right alongside you.', price: 149, category: 'work-bags', capacity: '14L', badge: 'NEW', features: ['Padded 16-inch laptop sleeve', 'Intuitive magnetic flap closure', 'Multiple internal organization pockets', 'Comfortable adjustable shoulder strap', 'Luggage pass-through for easy travel'], dimensions: '400 × 300 × 130 mm', tags: ['new-releases', 'work', 'classic', 'tech'], colors: colors('classic-messenger', [['Olive', '#68705b'], ['Black', '#343634'], ['Camel', '#b79a77']]) },
  { id: 'phone-case', name: 'Phone Case', subtitle: 'Protection with a personal touch', description: 'Super-slim, beautifully textured and made to feel right in your hand. This considered case keeps your phone protected without weighing you down.', price: 49, category: 'phone-cases', badge: 'NEW COLORS', features: ['Slim profile with protective polymer bumpers', 'Soft microfiber lining', 'Precision-cut camera and port openings', 'Easy-click covered buttons', 'Backed by a 3-year warranty'], dimensions: 'Designed for iPhone', tags: ['tech', 'for-tech-lovers', 'new-releases'], colors: [{ name: 'Canyon', hex: '#b56e54', stock: 31, images: ['/images/phone-case.jpg', '/images/phone-case-detail.jpg'] }] },
];
export const categories = [
  { id: 'all', name: 'Shop all', nameAr: 'تسوق الكل' }, { id: 'backpacks', name: 'Backpacks', nameAr: 'حقائب الظهر' },
  { id: 'crossbody-bags', name: 'Slings & Crossbody Bags', nameAr: 'حقائب الكتف والكروس' }, { id: 'wallets', name: 'Wallets', nameAr: 'محافظ' },
  { id: 'phone-cases', name: 'Phone Cases', nameAr: 'أغطية الهواتف' }, { id: 'luggage', name: 'Luggage', nameAr: 'حقائب السفر' },
  { id: 'work-bags', name: 'Work Bags', nameAr: 'حقائب العمل' }, { id: 'tote-bags', name: 'Tote & Shoulder Bags', nameAr: 'حقائب اليد والكتف' },
  { id: 'accessories', name: 'Accessories', nameAr: 'إكسسوارات' },
];
export const bagCategories = ['backpacks', 'crossbody-bags', 'tote-bags', 'work-bags', 'luggage'];
export const collectionNames: Record<string, string> = { bestsellers: 'The crowd favorites', 'new-releases': 'Fresh perspectives. New possibilities.', travel: 'Made for the journey', work: 'A better way to work', outdoor: 'Go a little further', campus: 'Ready for what’s next', tech: 'For all the ways you move.', 'for-tech-lovers': 'For all the ways you move.', transit: 'Meet the Transit Collection', venture: 'Adventure is calling', tokyo: 'City life, considered', classic: 'Classic for a reason', lite: 'Carry less. Do more.', cinch: 'An easy kind of everyday', laneway: 'Find your own way', 'value-sets': 'Better together', outlet: 'Good things. Better prices.' };
export const collectionNamesAr: Record<string, string> = { bestsellers: 'الأكثر طلباً', 'new-releases': 'إصدارات جديدة', travel: 'مصممة للرحلة', work: 'طريقة أفضل للعمل', outdoor: 'انطلق أبعد', campus: 'جاهز لما هو قادم', tech: 'لكل طرق تنقلك', 'for-tech-lovers': 'لكل طرق تنقلك', transit: 'مجموعة Transit', venture: 'المغامرة تنادي', tokyo: 'حياة المدينة بأسلوب مدروس', classic: 'كلاسيكية لسبب', lite: 'احمل أقل. افعل أكثر.', cinch: 'سهولة لكل يوم', laneway: 'اصنع طريقك الخاص', 'value-sets': 'أفضل معاً', outlet: 'أشياء جميلة بأسعار أفضل.' };

