import { redirect } from 'next/navigation';
import { cookies } from 'next/headers';
import { batchT, LANGUAGE_COOKIE, normalizeLanguage } from '@/lib/i18n';
import { requireAdminSection } from '@/lib/admin-auth';
import Link from 'next/link';
import { and, desc, gte, lte } from 'drizzle-orm';
import { ArrowRight, BarChart3, Boxes, CalendarDays, CircleDollarSign, Download, MapPin, Package, ShoppingCart, Tag, TrendingUp, Users, Truck, WalletCards } from 'lucide-react';
import { db } from '@/db';
import { customers, inventoryBatches, orders, productVariants, products, shippingZones } from '@/db/schema';
import { iqd, when } from '@/lib/format';
import { lineProductProfit, orderProductProfit, orderGrossRevenue } from '@/lib/orders';

type Item = { productId?: string; variantId?: number; name: string; color?: string; quantity: number; unitPrice?: number; profitIqd?: number | null; purchaseCostCents?: number | null; image?: string | null };
const liveStatuses = ['delivered'] as const;
const moneyNumber = (v: unknown) => { const n = Number(v); return Number.isFinite(n) ? n : 0; };
const itemsOf = (o: typeof orders.$inferSelect) => Array.isArray(o.items) ? o.items as Item[] : [];
const productGrossRevenue = (o: typeof orders.$inferSelect) => o.status === 'delivered' ? orderGrossRevenue(itemsOf(o)) : 0;
const productRevenue = (o: typeof orders.$inferSelect) => o.status === 'delivered' ? Math.max(0, productGrossRevenue(o) - moneyNumber(o.discountCents)) : 0;
const profitOf = (o: typeof orders.$inferSelect) => o.status === 'delivered' ? orderProductProfit(itemsOf(o), moneyNumber(o.discountCents)) : 0;
const costOf = (o: typeof orders.$inferSelect) => itemsOf(o).reduce((sum, item) => sum + (item.purchaseCostCents == null ? 0 : moneyNumber(item.purchaseCostCents) * moneyNumber(item.quantity)), 0);
const knownCostUnits = (o: typeof orders.$inferSelect) => itemsOf(o).reduce((sum, item) => sum + (item.purchaseCostCents == null ? 0 : moneyNumber(item.quantity)), 0);
const itemProfit = (item: Item, items: Item[], discount: number) => lineProductProfit(item, items, discount);
function startDate(value?: string) { if (value === 'today') { const d=new Date(); d.setHours(0,0,0,0); return d; } if (value === '7d') { const d=new Date(); d.setDate(d.getDate()-6); d.setHours(0,0,0,0); return d; } if (value === '90d') { const d=new Date(); d.setDate(d.getDate()-89); d.setHours(0,0,0,0); return d; } if (value === 'year') return new Date(new Date().getFullYear(),0,1); if (/^\d{4}-\d{2}-\d{2}$/.test(value||'')) return new Date(`${value}T00:00:00`); const d=new Date(); d.setDate(d.getDate()-29); d.setHours(0,0,0,0); return d; }
function endDate(value?: string) { if (/^\d{4}-\d{2}-\d{2}$/.test(value||'')) return new Date(`${value}T23:59:59.999`); const d=new Date(); d.setHours(23,59,59,999); return d; }
const pct = (n:number,d:number) => d ? `${Math.round(n/d*100)}%` : '0%';

export const metadata = { title: 'Reports' };
export const dynamic = 'force-dynamic';

export default async function ReportsPage({ searchParams }: { searchParams: Promise<{ period?: string; from?: string; to?: string; section?: string }> }) {
  const actor = await requireAdminSection('overview', 'view');
  if (!actor) redirect('/admin');
  const params=await searchParams; const cookieStore=await cookies(); const language=normalizeLanguage(cookieStore.get(LANGUAGE_COOKIE)?.value); const t=(x:string)=>batchT(x,language); const period=params.period||'30d'; const from=params.from?startDate(params.from):startDate(period); const to=params.to?endDate(params.to):endDate(); const section=params.section||'overview';
  const [allOrders,allProducts,allVariants,batches,allCustomers,zones]=await Promise.all([
    db.select().from(orders).where(and(gte(orders.createdAt,from),lte(orders.createdAt,to))).orderBy(desc(orders.createdAt)).limit(10000),
    db.select().from(products), db.select().from(productVariants), db.select().from(inventoryBatches), db.select().from(customers).orderBy(desc(customers.lastOrderAt)).limit(1000), db.select().from(shippingZones)
  ]);
  const live=allOrders.filter(o=>(liveStatuses as readonly string[]).includes(o.status)); const cancelled=allOrders.filter(o=>o.status==='cancelled'); const returned=allOrders.filter(o=>o.status==='returned');
  const revenue=live.reduce((s,o)=>s+productRevenue(o),0), delivery=live.reduce((s,o)=>s+moneyNumber(o.shippingCents),0), cost=live.reduce((s,o)=>s+costOf(o),0), profit=live.reduce((s,o)=>s+profitOf(o),0);
  const units=live.reduce((s,o)=>s+itemsOf(o).reduce((a,i)=>a+moneyNumber(i.quantity),0),0), knownUnits=live.reduce((s,o)=>s+knownCostUnits(o),0), discounts=live.reduce((s,o)=>s+moneyNumber(o.discountCents),0), avgOrder=live.length?revenue/live.length:0;
  const totalStock=allVariants.reduce((s,v)=>s+moneyNumber(v.stock),0), stockValue=batches.reduce((s,b)=>s+(b.purchaseCostIqd==null?0:moneyNumber(b.purchaseCostIqd)*moneyNumber(b.quantityRemaining)),0), unknownStockUnits=batches.reduce((s,b)=>s+(b.purchaseCostIqd==null?moneyNumber(b.quantityRemaining):0),0);
  const productMap=new Map(allProducts.map(p=>[p.id,p])), variantMap=new Map(allVariants.map(v=>[v.id,v])); const zoneName=(code:string)=>{const z=zones.find(x=>x.code===code);return language==='ar'?(z?.nameAr||z?.nameEn||code): (z?.nameEn||code)};
  const productAgg=new Map<string,{name:string;category:string;units:number;revenue:number;cost:number;profit:number;orders:number}>(), categoryAgg=new Map<string,{units:number;revenue:number;cost:number;profit:number;orders:number}>(), sourceAgg=new Map<string,{orders:number;revenue:number}>(), govAgg=new Map<string,{orders:number;revenue:number;delivery:number}>(), dayAgg=new Map<string,{orders:number;revenue:number;profit:number}>(), statusAgg=new Map<string,number>(), variantAgg=new Map<number,{name:string;product:string;units:number;revenue:number}>();
  for(const o of allOrders){statusAgg.set(o.status,(statusAgg.get(o.status)??0)+1);if(!(liveStatuses as readonly string[]).includes(o.status))continue;const or=productRevenue(o),src=o.source||'website',s=sourceAgg.get(src)??{orders:0,revenue:0};s.orders++;s.revenue+=or;sourceAgg.set(src,s);const g=govAgg.get(o.governorate)??{orders:0,revenue:0,delivery:0};g.orders++;g.revenue+=or;g.delivery+=moneyNumber(o.shippingCents);govAgg.set(o.governorate,g);const day=new Date(o.createdAt).toISOString().slice(0,10),d=dayAgg.get(day)??{orders:0,revenue:0,profit:0};d.orders++;d.revenue+=or;d.profit+=profitOf(o);dayAgg.set(day,d);const grossOrderRevenue=productGrossRevenue(o),orderDiscount=Math.min(Math.max(0,moneyNumber(o.discountCents)),grossOrderRevenue); for(const item of itemsOf(o)){const qty=moneyNumber(item.quantity),line=moneyNumber(item.unitPrice)*qty,netLine=grossOrderRevenue>0?Math.max(0,line-(orderDiscount*(line/grossOrderRevenue))):0,p=productMap.get(item.productId||''),name=language==='ar'?(p?.nameAr||p?.name||item.name||'منتج غير محدد'):(p?.name||item.name||'Unknown product'),cat=p?.category||'other',pa=productAgg.get(item.productId||item.name)??{name,category:cat,units:0,revenue:0,cost:0,profit:0,orders:0};pa.units+=qty;pa.revenue+=netLine;pa.cost+=item.purchaseCostCents==null?0:moneyNumber(item.purchaseCostCents)*qty;pa.profit+=itemProfit(item,itemsOf(o),orderDiscount);pa.orders++;productAgg.set(item.productId||item.name,pa);const ca=categoryAgg.get(cat)??{units:0,revenue:0,cost:0,profit:0,orders:0};ca.units+=qty;ca.revenue+=netLine;ca.cost+=item.purchaseCostCents==null?0:moneyNumber(item.purchaseCostCents)*qty;ca.profit+=itemProfit(item,itemsOf(o),orderDiscount);ca.orders++;categoryAgg.set(cat,ca);if(item.variantId){const v=variantMap.get(item.variantId),va=variantAgg.get(item.variantId)??{name:item.color||v?.name||'Variant',product:name,units:0,revenue:0};va.units+=qty;va.revenue+=netLine;variantAgg.set(item.variantId,va)}}}
  const topProducts=[...productAgg.values()].sort((a,b)=>b.units-a.units || b.revenue-a.revenue).slice(0,10),topVariants=[...variantAgg.values()].sort((a,b)=>b.units-a.units).slice(0,10),categories=[...categoryAgg.entries()].sort((a,b)=>b[1].revenue-a[1].revenue),sources=[...sourceAgg.entries()].sort((a,b)=>b[1].revenue-a[1].revenue),governors=[...govAgg.entries()].sort((a,b)=>b[1].orders-a[1].orders),days=[...dayAgg.entries()].sort((a,b)=>a[0].localeCompare(b[0]));
  const maxDay=Math.max(...days.map(x=>x[1].revenue),1),repeatCustomers=allCustomers.filter(c=>c.ordersCount>=2).length,inactiveCustomers=allCustomers.filter(c=>c.lastOrderAt&&Date.now()-new Date(c.lastOrderAt).getTime()>=90*86400000).length,newCustomers=allCustomers.filter(c=>c.createdAt>=from&&c.createdAt<=to).length,marketingOptIn=allCustomers.filter(c=>c.marketingOptIn).length,lowStock=allVariants.filter(v=>v.stock>0&&v.stock<=5).length,soldOut=allVariants.filter(v=>v.stock===0).length;
  const dateLabel=`${from.toLocaleDateString('en-GB')} – ${to.toLocaleDateString('en-GB')}`; const tabs=[['overview',t('Executive')],['sales',t('Sales')],['profit',t('Profit')],['inventory',t('Inventory')],['products',t('Products')],['customers',t('Customers')],['orders',t('Orders')],['delivery',t('Delivery')],['discounts',t('Coupons')]]; const href=(s:string)=>`/admin/reports?period=${encodeURIComponent(period)}&section=${s}`;
  return <main className="admin-page"><div className="admin-page-heading"><div><span className="admin-eyebrow"><BarChart3 size={12}/> {t('Analytics · Reports')}</span><h1>{t('Reports')}</h1><p>{t('Full operational reporting for sales, profit, inventory, products, customers, orders and delivery. Product revenue excludes delivery charges.')}</p></div><div className="admin-heading-actions"><span className="admin-report-date"><CalendarDays size={15}/>{dateLabel}</span><a href={`/api/admin/reports/export?period=${encodeURIComponent(period)}${params.from?`&from=${encodeURIComponent(params.from)}`:""}${params.to?`&to=${encodeURIComponent(params.to)}`:""}`} className="admin-btn admin-btn-primary"><Download size={15}/> {t('Export Excel')}</a><Link href="/admin" className="admin-btn admin-btn-ghost">{t('Dashboard')} <ArrowRight size={15}/></Link></div></div>
    <div className="admin-report-filters"><div className="admin-report-periods">{[['today',t('Today')],['7d',t('7 days')],['30d',t('30 days')],['90d',t('90 days')],['year',t('This year')]].map(([key,label])=><Link key={key} href={`/admin/reports?period=${key}&section=${section}`} className={period===key&&!params.from?'active':''}>{label}</Link>)}</div><form className="admin-report-custom" method="get"><input type="hidden" name="section" value={section}/><label>{t('From')}<input type="date" name="from" defaultValue={params.from||from.toISOString().slice(0,10)}/></label><label>{t('To')}<input type="date" name="to" defaultValue={params.to||to.toISOString().slice(0,10)}/></label><button className="admin-btn admin-btn-primary" type="submit">{t('Apply')}</button></form></div>
    <div className="admin-report-tabs">{tabs.map(([key,label])=><Link key={key} href={href(key)} className={section===key?'active':''}>{label}</Link>)}</div>
    {section==='overview'&&<><div className="admin-stats">{[['Product revenue',iqd(revenue),t('Delivered products only'),WalletCards],['Product profit',iqd(profit),t('Recognized on delivered orders'),TrendingUp],['Delivery collected',iqd(delivery),'Delivered orders only',Truck],['Orders',live.length.toLocaleString(),t('Delivered orders'),ShoppingCart],[t('Units sold'),units.toLocaleString(),t('Across all products'),Package],['Average order',iqd(avgOrder),t('Product revenue / order'),CircleDollarSign],['Discounts',iqd(discounts),t('Applied to delivered orders'),Tag],[t('Stock value'),iqd(stockValue),unknownStockUnits?`${unknownStockUnits} units unknown cost`:'Purchase cost basis',Boxes]].map(([label,value,note,Icon])=><div className="admin-stat" key={String(label)}><Icon size={20} strokeWidth={1.5}/><strong>{String(value)}</strong><span>{String(label)}</span><small>{String(note)}</small></div>)}</div><div className="admin-grid-2"><section className="admin-card"><div className="admin-card-heading"><h2><TrendingUp size={17}/> Revenue by day</h2></div><div className="admin-report-bars">{days.length?days.map(([day,v])=><div className="admin-report-bar-col" key={day} title={`${day}: ${iqd(v.revenue)} revenue · ${iqd(v.profit)} profit`}><i style={{height:`${Math.max(v.revenue/maxDay*100,v.orders?4:1)}%`}}/><span>{day.slice(5)}</span></div>):<p className="admin-empty">No orders in this period.</p>}</div></section><section className="admin-card"><div className="admin-card-heading"><h2><Package size={17}/> Product mix</h2></div>{categories.length?<table className="admin-table"><thead><tr><th>{t('Category')}</th><th className="num">{t('Units')}</th><th className="num">{t('Revenue')}</th><th className="num">{t('Profit')}</th></tr></thead><tbody>{categories.map(([cat,v])=><tr key={cat}><td>{cat}</td><td className="num">{v.units}</td><td className="num">{iqd(v.revenue)}</td><td className="num">{iqd(v.profit)}</td></tr>)}</tbody></table>:<p className="admin-empty">No sales yet.</p>}</section></div><div className="admin-grid-2"><section className="admin-card"><div className="admin-card-heading"><h2><ShoppingCart size={17}/> Order status</h2></div><table className="admin-table"><tbody>{[...statusAgg.entries()].sort((a,b)=>b[1]-a[1]).map(([s,n])=><tr key={s}><td>{s}</td><td className="num">{n}</td><td className="num">{pct(n,allOrders.length)}</td></tr>)}</tbody></table></section><section className="admin-card"><div className="admin-card-heading"><h2><Users size={17}/> Customer snapshot</h2><Link className="admin-link" href="/admin/customers">CRM <ArrowRight size={14}/></Link></div><div className="admin-report-mini-grid">{[[allCustomers.length,'Total customers'],[newCustomers,'New in period'],[repeatCustomers,'Repeat customers'],[inactiveCustomers,'Inactive 90+ days'],[marketingOptIn,'Marketing opt-in'],[soldOut,'Sold out variants']].map(([n,l])=><div key={String(l)}><strong>{String(n)}</strong><span>{String(l)}</span></div>)}</div></section></div></>}
    {section==='sales'&&<section className="admin-card"><div className="admin-card-heading"><h2><CircleDollarSign size={17}/> Sales report</h2></div><div className="admin-stats admin-stats-compact">{[[iqd(revenue),'Revenue'],[units,'Units'],[iqd(discounts),'Discounts'],[iqd(avgOrder),'Average order']].map(([v,l])=><div className="admin-stat" key={String(l)}><strong>{String(v)}</strong><span>{String(l)}</span></div>)}</div><div className="admin-grid-2"><div><h3 className="admin-report-subtitle">{t('By source')}</h3><table className="admin-table"><thead><tr><th>{t('Source')}</th><th className="num">{t('Orders')}</th><th className="num">{t('Revenue')}</th></tr></thead><tbody>{sources.map(([s,v])=><tr key={s}><td>{s}</td><td className="num">{v.orders}</td><td className="num">{iqd(v.revenue)}</td></tr>)}</tbody></table></div><div><h3 className="admin-report-subtitle">{t('By governorate')}</h3><table className="admin-table"><thead><tr><th>Governorate</th><th className="num">{t('Orders')}</th><th className="num">{t('Revenue')}</th></tr></thead><tbody>{governors.map(([g,v])=><tr key={g}><td>{zoneName(g)}</td><td className="num">{v.orders}</td><td className="num">{iqd(v.revenue)}</td></tr>)}</tbody></table></div></div></section>}
    {section==='profit'&&<><section className="admin-card"><div className="admin-card-heading"><h2><TrendingUp size={17}/> {t('Profit report')}</h2></div><div className="admin-stats admin-stats-compact">{[[iqd(revenue),t('Product revenue')],[iqd(profit),t('Product profit')],[pct(profit,revenue),t('Profit margin')],[iqd(cost),t('Inventory cost')]].map(([v,l])=><div className="admin-stat" key={String(l)}><strong>{String(v)}</strong><span>{String(l)}</span></div>)}</div><p className="admin-footnote">{t('Product profit formula')}</p></section><section className="admin-card"><div className="admin-card-heading"><h2>{t('Profit by product')}</h2></div><table className="admin-table admin-products-table"><thead><tr><th>{t('Product')}</th><th>{t('Category')}</th><th className="num">{t('Units')}</th><th className="num">{t('Revenue')}</th><th className="num">{t('Cost')}</th><th className="num">{t('Profit')}</th><th className="num">{t('Margin')}</th></tr></thead><tbody>{topProducts.map(p=><tr key={p.name}><td>{p.name}</td><td>{language==='ar' ? ({backpacks:'حقائب',bags:'حقائب',wallets:'محافظ',accessories:'إكسسوارات',other:'أخرى'} as Record<string,string>)[p.category] || p.category : p.category}</td><td className="num">{p.units}</td><td className="num">{iqd(p.revenue)}</td><td className="num">{iqd(p.cost)}</td><td className="num">{iqd(p.profit)}</td><td className="num">{pct(p.profit,p.revenue)}</td></tr>)}</tbody></table></section></>}
    {section==='inventory'&&<><div className="admin-stats">{[[totalStock,'Units in stock'],[iqd(stockValue),'Stock cost value'],[batches.length,'Batches'],[lowStock,'Low stock variants'],[soldOut,'Sold out variants']].map(([v,l])=><div className="admin-stat" key={String(l)}><Boxes size={20}/><strong>{String(v)}</strong><span>{String(l)}</span></div>)}</div><section className="admin-card"><div className="admin-card-heading"><h2><Boxes size={17}/> Batch inventory</h2><Link href="/admin/inventory" className="admin-link">Manage inventory <ArrowRight size={14}/></Link></div><table className="admin-table admin-products-table"><thead><tr><th>Batch</th><th>Product / variant</th><th className="num">{t('Received')}</th><th className="num">{t('Remaining')}</th><th className="num">{t('Purchase cost')}</th><th className="num">{t('Sale price')}</th><th>{t('Received at')}</th></tr></thead><tbody>{[...batches].sort((a,b)=>new Date(b.receivedAt).getTime()-new Date(a.receivedAt).getTime()).slice(0,100).map(b=>{const v=variantMap.get(b.variantId),p=v?productMap.get(v.productId):null;return <tr key={b.id}><td>{b.batchNumber}</td><td>{p?.name||'—'}<br/><small>{v?.name||'—'}</small></td><td className="num">{b.quantityReceived}</td><td className="num">{b.quantityRemaining}</td><td className="num">{b.purchaseCostIqd==null?'—':iqd(b.purchaseCostIqd)}</td><td className="num">{b.salePriceIqd==null?(b.salePriceCents==null?'—':iqd(b.salePriceCents)):iqd(b.salePriceIqd)}</td><td>{when(b.receivedAt)}</td></tr>})}</tbody></table></section></>}
    {section==='products'&&<section className="admin-card"><div className="admin-card-heading"><h2><Package size={17}/> Product performance</h2></div><table className="admin-table admin-products-table"><thead><tr><th>{t('Product')}</th><th>{t('Category')}</th><th className="num">{t('Units')}</th><th className="num">{t('Revenue')}</th><th className="num">{t('Cost')}</th><th className="num">{t('Profit')}</th><th className="num">{t('Orders')}</th></tr></thead><tbody>{topProducts.map(p=><tr key={p.name}><td>{p.name}</td><td>{language==='ar' ? ({backpacks:'حقائب',bags:'حقائب',wallets:'محافظ',accessories:'إكسسوارات',other:'أخرى'} as Record<string,string>)[p.category] || p.category : p.category}</td><td className="num">{p.units}</td><td className="num">{iqd(p.revenue)}</td><td className="num">{iqd(p.cost)}</td><td className="num">{iqd(p.profit)}</td><td className="num">{p.orders}</td></tr>)}</tbody></table><div className="admin-report-divider"/><h3 className="admin-report-subtitle">{t('Top variants / colours')}</h3><table className="admin-table"><thead><tr><th>{t('Variant')}</th><th>{t('Product')}</th><th className="num">{t('Units')}</th><th className="num">{t('Revenue')}</th></tr></thead><tbody>{topVariants.map(v=><tr key={`${v.product}-${v.name}`}><td>{v.name}</td><td>{v.product}</td><td className="num">{v.units}</td><td className="num">{iqd(v.revenue)}</td></tr>)}</tbody></table></section>}
    {section==='customers'&&<section className="admin-card"><div className="admin-card-heading"><h2><Users size={17}/> Customer report</h2><Link className="admin-link" href="/admin/customers">Open CRM <ArrowRight size={14}/></Link></div><div className="admin-stats admin-stats-compact">{[[allCustomers.length,'Total customers'],[newCustomers,'New in period'],[repeatCustomers,'Repeat'],[inactiveCustomers,'Inactive 90+ days']].map(([v,l])=><div className="admin-stat" key={String(l)}><strong>{String(v)}</strong><span>{String(l)}</span></div>)}</div><table className="admin-table"><thead><tr><th>{t('Customer')}</th><th>{t('Phone')}</th><th className="num">{t('Orders')}</th><th className="num">{t('Product spend')}</th><th>{t('Last order')}</th><th>{t('Channel')}</th></tr></thead><tbody>{allCustomers.slice(0,100).map(c=><tr key={c.id}><td>{c.name}</td><td>{c.phone}</td><td className="num">{c.ordersCount}</td><td className="num">{iqd(c.totalSpent)}</td><td>{c.lastOrderAt?when(c.lastOrderAt):'—'}</td><td>{c.preferredChannel}</td></tr>)}</tbody></table></section>}
    {section==='orders'&&<section className="admin-card"><div className="admin-card-heading"><h2><ShoppingCart size={17}/> Orders report</h2><Link className="admin-link" href="/admin/orders">Manage orders <ArrowRight size={14}/></Link></div><table className="admin-table"><thead><tr><th>{t('Reference')}</th><th>{t('Customer')}</th><th>{t('Source')}</th><th>{t('Status')}</th><th className="num">{t('Products')}</th><th className="num">{t('Profit')}</th><th className="num">{t('Delivery')}</th><th>{t('Date')}</th></tr></thead><tbody>{allOrders.slice(0,200).map(o=><tr key={o.id}><td>{o.reference}</td><td>{o.name}<br/><small>{o.phone}</small></td><td>{o.source}</td><td><span className={`admin-badge ${o.status==='delivered'?'success':o.status==='cancelled'||o.status==='returned'?'danger':'warning'}`}>{o.status}</span></td><td className="num">{iqd(productRevenue(o))}</td><td className="num">{iqd(profitOf(o))}</td><td className="num">{iqd(o.shippingCents)}</td><td>{when(o.createdAt)}</td></tr>)}</tbody></table></section>}
    {section==='delivery'&&<section className="admin-card"><div className="admin-card-heading"><h2><MapPin size={17}/> Delivery & governorates</h2><Link className="admin-link" href="/admin/shipping">Delivery settings <ArrowRight size={14}/></Link></div><table className="admin-table"><thead><tr><th>Governorate</th><th className="num">{t('Orders')}</th><th className="num">{t(t('Product revenue'))}</th><th className="num">{t('Delivery collected')}</th><th className="num">{t('Delivered')}</th></tr></thead><tbody>{governors.map(([g,v])=><tr key={g}><td>{zoneName(g)}</td><td className="num">{v.orders}</td><td className="num">{iqd(v.revenue)}</td><td className="num">{iqd(v.delivery)}</td><td className="num">{allOrders.filter(o=>o.governorate===g&&o.status==='delivered').length}</td></tr>)}</tbody></table><p className="admin-footnote">{t('Delivery collections are shown separately and are not included in product revenue or profit.')}</p></section>}
    {section==='discounts'&&<section className="admin-card"><div className="admin-card-heading"><h2><Tag size={17}/> Discounts & coupons</h2><Link className="admin-link" href="/admin/coupons">Manage coupons <ArrowRight size={14}/></Link></div><div className="admin-stats admin-stats-compact">{[[iqd(discounts),'Total discounts'],[live.filter(o=>moneyNumber(o.discountCents)>0).length,'Orders discounted'],[pct(discounts,revenue+discounts),'Discount rate']].map(([v,l])=><div className="admin-stat" key={String(l)}><strong>{String(v)}</strong><span>{String(l)}</span></div>)}</div><table className="admin-table"><thead><tr><th>{t('Order')}</th><th>{t('Customer')}</th><th>{t('Coupon')}</th><th className="num">{t('Discount')}</th><th>{t('Date')}</th></tr></thead><tbody>{live.filter(o=>moneyNumber(o.discountCents)>0).map(o=><tr key={o.id}><td>{o.reference}</td><td>{o.name}</td><td>{o.couponCode||'Manual discount'}</td><td className="num">{iqd(o.discountCents)}</td><td>{when(o.createdAt)}</td></tr>)}</tbody></table></section>}
    <div className="admin-report-footer"><span>{t('Reporting period')}: {dateLabel} · {allOrders.length} {t('total orders')} · {cancelled.length} {t('cancelled')} · {returned.length} {t('returned')}</span><span><Download size={14}/> {t('Export-ready structure')}</span></div>
  </main>;
}
