import { NextRequest, NextResponse } from 'next/server';
import { asc, eq } from 'drizzle-orm';
import { db } from '@/db';
import { urlRedirects } from '@/db/schema';
import { requireAdminSection } from '@/lib/admin-auth';
import { logActivity } from '@/lib/orders';
export const dynamic='force-dynamic';
const cleanPath=(v:unknown)=>{const x=String(v??'').trim();return x&&x.startsWith('/')&&!x.startsWith('//')&&!/[\n\r]/.test(x)?x.slice(0,500):''};
export async function GET(){if(!(await requireAdminSection('configuration','view')))return NextResponse.json({error:'Forbidden'},{status:403});return NextResponse.json({items:await db.select().from(urlRedirects).orderBy(asc(urlRedirects.sourcePath))})}
export async function POST(req:NextRequest){if(!(await requireAdminSection('configuration','manage')))return NextResponse.json({error:'Forbidden'},{status:403});const b=await req.json().catch(()=>({}));const sourcePath=cleanPath(b.sourcePath),destinationPath=cleanPath(b.destinationPath),statusCode=Number(b.statusCode)===302?302:301,active=b.active!==false;if(!sourcePath||sourcePath==='/'||!destinationPath||sourcePath===destinationPath)return NextResponse.json({error:'Source and destination must be valid and different paths.'},{status:400});try{const[row]=await db.insert(urlRedirects).values({sourcePath,destinationPath,statusCode,active}).returning();await logActivity('redirect.create','url_redirects',String(row.id),`${sourcePath} → ${destinationPath}`);return NextResponse.json({item:row})}catch{return NextResponse.json({error:'A redirect with this source path already exists.'},{status:400})}}
export async function PUT(req:NextRequest){if(!(await requireAdminSection('configuration','manage')))return NextResponse.json({error:'Forbidden'},{status:403});const b=await req.json().catch(()=>({}));const id=Number(b.id),sourcePath=cleanPath(b.sourcePath),destinationPath=cleanPath(b.destinationPath),statusCode=Number(b.statusCode)===302?302:301,active=b.active!==false;if(!Number.isInteger(id)||!sourcePath||sourcePath==='/'||!destinationPath||sourcePath===destinationPath)return NextResponse.json({error:'Invalid redirect.'},{status:400});try{const[row]=await db.update(urlRedirects).set({sourcePath,destinationPath,statusCode,active,updatedAt:new Date()}).where(eq(urlRedirects.id,id)).returning();if(!row)return NextResponse.json({error:'Redirect not found.'},{status:404});await logActivity('redirect.update','url_redirects',String(id),`${sourcePath} → ${destinationPath}`);return NextResponse.json({item:row})}catch{return NextResponse.json({error:'A redirect with this source path already exists.'},{status:400})}}
export async function DELETE(req:NextRequest){if(!(await requireAdminSection('configuration','manage')))return NextResponse.json({error:'Forbidden'},{status:403});const b=await req.json().catch(()=>({}));const id=Number(b.id);if(!Number.isInteger(id))return NextResponse.json({error:'Invalid redirect.'},{status:400});const[row]=await db.delete(urlRedirects).where(eq(urlRedirects.id,id)).returning();if(!row)return NextResponse.json({error:'Redirect not found.'},{status:404});await logActivity('redirect.delete','url_redirects',String(id),row.sourcePath);return NextResponse.json({ok:true})}
