'use client';
import { useState } from 'react';
import { useLanguage } from '@/components/language-provider';
import { batchT } from '@/lib/i18n';
import { AlertTriangle, Download, RefreshCcw, ShieldCheck } from 'lucide-react';
import { useFlash } from './ui';
export function BackupManager() {
  const { language } = useLanguage(); const t=(x:string)=>batchT(x,language);
  const [busy,setBusy]=useState(false); const [file,setFile]=useState<File|null>(null); const [confirm,setConfirm]=useState(''); const {flash,fail}=useFlash();
  async function createBackup(){setBusy(true);try{const res=await fetch('/api/admin/backup');if(!res.ok)throw new Error((await res.json()).error||t('Backup failed'));const blob=await res.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`bellroy-backup-${new Date().toISOString().replace(/[:.]/g,'-')}.json`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);}catch(e){fail(e)}finally{setBusy(false)}}
  async function restore(){if(!file)return;setBusy(true);try{const fd=new FormData();fd.append('file',file);fd.append('confirmation',confirm);const res=await fetch('/api/admin/backup/restore',{method:'POST',body:fd});const data=await res.json();if(!res.ok)throw new Error(data.error||t('Restore failed'));alert(t('Backup restored successfully. The page will refresh.'));location.href='/admin';}catch(e){fail(e)}finally{setBusy(false)}}
  return <>{flash}<div className="admin-grid-2"><section className="admin-card"><div className="admin-card-heading"><div><h2><Download size={17}/> Create backup</h2><p className="admin-hint">{t('Downloads all public application data, including products, orders, customers, inventory, settings, media and team accounts.')}</p></div></div><button className="admin-btn admin-btn-primary" onClick={()=>void createBackup()} disabled={busy}><Download size={16}/>{busy?t('Creating…'):t('Download backup')}</button></section><section className="admin-card"><div className="admin-card-heading"><div><h2><RefreshCcw size={17}/> Restore backup</h2><p className="admin-hint">{t('Restore is owner-only and replaces the current database data with the selected backup.')}</p></div></div><div className="admin-warning"><AlertTriangle size={18}/><div><strong>{t('This action is destructive.')}</strong><p>{t('Make a fresh backup first. Restoring will replace current data.')}</p></div></div><label className="admin-field"><span>{t('Backup file')}</span><input type="file" accept="application/json,.json" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><label className="admin-field"><span>{t('Type RESTORE to confirm')}</span><input value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="RESTORE" autoComplete="off"/></label><button className="admin-btn admin-btn-danger" onClick={()=>void restore()} disabled={busy||!file||confirm!=='RESTORE'}><RefreshCcw size={16}/>{busy?t('Restoring…'):t('Restore backup')}</button></section></div><section className="admin-card" style={{marginTop:18}}><div className="admin-card-heading"><div><h2><ShieldCheck size={17}/> Backup policy</h2><p className="admin-hint">{t('Only the Owner can create or restore backups. Team members cannot access these actions through the UI or API.')}</p></div></div><ul className="admin-list"><li>{t('Backup format: JSON')}</li><li>{t('Maximum restore file size: 50 MB')}</li><li>{t('Passwords remain hashed; no plaintext passwords are exported.')}</li><li>{t('Media binary data is included in the backup.')}</li></ul></section></>;
}
