'use client';
import Link from 'next/link';
import { ArrowRight, Calculator, CircleDollarSign, Plus, TrendingDown, WalletCards } from 'lucide-react';
import { useLanguage } from '@/components/language-provider';
import { batchT, storefrontT } from '@/lib/i18n';

type ExpenseRow={id:number;expenseDate:string|Date;description:string;reference:string|null;category:string;paymentMethod:string;amountIqd:number};
const iqd=(v:number)=>new Intl.NumberFormat('en-IQ').format(Number(v)||0)+' IQD';
const when=(v:string|Date)=>new Date(v).toLocaleDateString('en-GB');
const label=(v:string)=>v.replace(/(^|_)/g,(_,a)=>a?' ':'').replace(/^./,x=>x.toUpperCase());
export default function FinanceClient({rows,revenue,productCost,totalExpenses,net,grossProfit,totalPurchases,stockValue,unknownStockUnits,byCat,period}:{rows:ExpenseRow[];revenue:number;productCost:number;totalExpenses:number;net:number;grossProfit:number;totalPurchases:number;stockValue:number;unknownStockUnits:number;byCat:[string,number][];period:string}){
 const {language}=useLanguage(); const t=(s:string)=>batchT(s,language);
 const periods=[['today','Today'],['7d','7 days'],['30d','30 days'],['90d','90 days'],['year','Year']];
 const cats=(c:string)=>t(c.charAt(0).toUpperCase()+c.slice(1));
 return <main className="admin-page"><div className="admin-page-heading"><div><span className="admin-eyebrow"><CircleDollarSign size={12}/> {t('Finance')}</span><h1>{t('Finance')}</h1><p>{t('Track business expenses separately from product revenue and delivery collections.')}</p></div><div className="admin-heading-actions"><Link href="/admin/reports" className="admin-btn admin-btn-ghost">{t('Reports')} <ArrowRight size={15}/></Link></div></div>
 <div className="admin-filter-bar">{periods.map(([v,l])=><Link key={v} href={`?period=${v}`} className="admin-btn admin-btn-ghost">{t(l)}</Link>)}</div>
 <div className="admin-stats"><div className="admin-stat"><CircleDollarSign size={20}/><strong>{iqd(revenue)}</strong><span>{t('Product revenue')}</span></div><div className="admin-stat"><TrendingDown size={20}/><strong>{iqd(productCost)}</strong><span>{t('Product cost')}</span></div><div className="admin-stat"><WalletCards size={20}/><strong>{iqd(totalExpenses)}</strong><span>{t('Operating expenses')}</span></div><div className="admin-stat"><Calculator size={20}/><strong>{iqd(grossProfit)}</strong><span>{t('Gross profit')}</span></div><div className="admin-stat"><Calculator size={20}/><strong>{iqd(net)}</strong><span>{t('Net profit')}</span></div><div className="admin-stat"><WalletCards size={20}/><strong>{iqd(totalPurchases)}</strong><span>{t('Purchases')}</span></div><div className="admin-stat"><WalletCards size={20}/><strong>{iqd(stockValue)}</strong><span>{t('Current stock value')}</span><small>{unknownStockUnits ? `${unknownStockUnits} ${t('units without known cost')}` : t('Purchase cost basis')}</small></div></div>
 <section className="admin-card"><div className="admin-card-heading"><div><h2>{t('How profit is calculated')}</h2><p>{t('Net profit uses the cost of units actually sold (FIFO), not all purchases. Purchases are shown separately as cash/inventory investment. Remaining units stay in stock value until sold.')}</p></div></div><div className="admin-grid-2"><div><strong>{t('Revenue')}</strong><div>{iqd(revenue)}</div></div><div><strong>{t('Cost of goods sold')}</strong><div>{iqd(productCost)}</div></div><div><strong>{t('Gross profit')}</strong><div>{iqd(grossProfit)}</div></div><div><strong>{t('Operating expenses')}</strong><div>{iqd(totalExpenses)}</div></div><div><strong>{t('Net profit')}</strong><div>{iqd(net)}</div></div><div><strong>{t('Purchases in period')}</strong><div>{iqd(totalPurchases)}</div></div></div></section><div className="admin-grid-2"><section className="admin-card"><div className="admin-card-heading"><div><h2>{t('Operating expenses')}</h2><p className="admin-card-subtitle">{t('Costs that reduce business net profit.')}</p></div><a href="#add-expense" className="admin-btn admin-btn-primary"><Plus size={15}/> {t('Add expense')}</a></div><table className="admin-table"><thead><tr><th>{t('Date')}</th><th>{t('Description')}</th><th>{t('Category')}</th><th>{t('Payment')}</th><th className="num">{t('Amount')}</th></tr></thead><tbody>{rows.map(e=><tr key={e.id}><td>{when(e.expenseDate)}</td><td>{e.description}{e.reference&&<><br/><small>{e.reference}</small></>}</td><td>{cats(e.category)}</td><td>{cats(e.paymentMethod)}</td><td className="num">{iqd(e.amountIqd)}</td></tr>)}{!rows.length&&<tr><td colSpan={5}>{t('No expenses in this period.')}</td></tr>}</tbody></table></section>
 <section className="admin-card"><div className="admin-card-heading"><h2>{t('By category')}</h2></div><table className="admin-table"><thead><tr><th>{t('Category')}</th><th className="num">{t('Amount')}</th></tr></thead><tbody>{byCat.map(([c,v])=><tr key={c}><td>{cats(c)}</td><td className="num">{iqd(v)}</td></tr>)}{!byCat.length&&<tr><td colSpan={2}>{t('No categorized expenses yet.')}</td></tr>}</tbody></table><p className="admin-footnote">{t('Customer delivery collections remain separate and are not treated as product revenue or profit.')}</p></section></div>
 <section id="add-expense" className="admin-card"><div className="admin-card-heading"><div><h2>{t('Add expense')}</h2><p className="admin-card-subtitle">{t('Record marketing, salaries, rent, software and other business costs.')}</p></div></div><form className="admin-form-grid" action="/api/admin/expenses" method="post"><label>{t('Description')}<input name="description" required placeholder={t('Meta ads, rent, packaging...')} /></label><label>{t('Amount (IQD)')}<input name="amountIqd" type="number" min="1" required /></label><label>{t('Category')}<select name="category">{['marketing','advertising','packaging','salary','rent','software','delivery','photography','operations','other'].map(c=><option key={c} value={c}>{cats(c)}</option>)}</select></label><label>{t('Payment method')}<select name="paymentMethod">{['cash','bank','card','transfer','other'].map(c=><option key={c} value={c}>{cats(c)}</option>)}</select></label><label>{t('Date')}<input name="expenseDate" type="date" required defaultValue={new Date().toISOString().slice(0,10)} /></label><label>{t('Reference')}<input name="reference" placeholder={t('Invoice / receipt')} /></label><label className="admin-form-wide">{t('Notes')}<textarea name="notes" rows={3}/></label><div className="admin-form-actions"><button className="admin-btn admin-btn-primary" type="submit">{t('Save expense')}</button></div></form></section></main>;
}
