'use client';
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { ArrowDown, ArrowUp, LoaderCircle, Plus, Save, Trash2 } from 'lucide-react';
import type { FooterConfig, FooterGroup } from '@/lib/settings';
import { useLanguage } from '@/components/language-provider';
import { batchT } from '@/lib/i18n';
import { api, Field, useFlash } from './ui';

function blankGroup(): FooterGroup { return { title: '', titleAr: '', links: [{ label: '', labelAr: '', href: '/' }] }; }
export function FooterManager({ initial }: { initial: FooterConfig }) {
  const router = useRouter(); const { language } = useLanguage(); const t=(x:string)=>batchT(x,language); const { flash, success, fail } = useFlash(); const [data, setData] = useState(initial); const [saving, setSaving] = useState(false);
  const updateGroup=(i:number,p:Partial<FooterGroup>)=>setData(d=>({...d,groups:d.groups.map((g,j)=>j===i?{...g,...p}:g)}));
  const updateLink=(gi:number,li:number,p:any)=>setData(d=>({...d,groups:d.groups.map((g,j)=>j===gi?{...g,links:g.links.map((l,k)=>k===li?{...l,...p}:l)}:g)}));
  const moveGroup=(i:number,dir:-1|1)=>{const j=i+dir;if(j<0||j>=data.groups.length)return;const groups=[...data.groups];[groups[i],groups[j]]=[groups[j],groups[i]];setData({...data,groups});};
  async function save(){setSaving(true);try{await api('/api/admin/settings',{method:'PUT',json:{footer:data}});success('Footer saved. The storefront now reflects the changes.');router.refresh();}catch(e){fail(e)}finally{setSaving(false)}}
  return <>{flash}
    <section className="admin-card"><div className="admin-card-heading"><div><h2>{t('Footer link groups')}</h2><p className="admin-hint" style={{margin:'4px 0 0'}}>{t('Manage footer columns, links and their order.')}</p></div><button className="admin-btn admin-btn-primary admin-btn-sm" onClick={()=>setData(d=>({...d,groups:[...d.groups,blankGroup()]}))}><Plus size={14}/> {t('Add column')}</button></div>
      <div style={{display:'grid',gap:16}}>{data.groups.map((g,i)=><article key={i} className="admin-card" style={{margin:0,border:'1px solid var(--admin-border)'}}><div className="admin-card-heading"><strong>{g.title||`Column ${i+1}`}</strong><div style={{display:'flex',gap:6}}><button className="admin-icon-btn" disabled={i===0} onClick={()=>moveGroup(i,-1)}><ArrowUp size={15}/></button><button className="admin-icon-btn" disabled={i===data.groups.length-1} onClick={()=>moveGroup(i,1)}><ArrowDown size={15}/></button><button className="admin-icon-btn danger" onClick={()=>setData(d=>({...d,groups:d.groups.filter((_,j)=>j!==i)}))}><Trash2 size={15}/></button></div></div><div className="admin-form-grid"><Field label={language === 'ar' ? 'عنوان العمود — English' : 'Column title — English'}><input value={g.title} onChange={e=>updateGroup(i,{title:e.target.value})} placeholder="Help"/></Field><Field label={language === 'ar' ? 'عنوان العمود — العربية' : 'Column title — Arabic'}><input dir="rtl" value={g.titleAr ?? ''} onChange={e=>updateGroup(i,{titleAr:e.target.value})} placeholder="المساعدة"/></Field></div><div className="admin-form-grid" style={{marginTop:12}}><div className="span-2"><h3 className="admin-subheading">{t('Links')}</h3>{g.links.map((l,j)=><div className="admin-section-row" key={j}><input value={l.label} placeholder={language === 'ar' ? 'اسم الرابط — English' : 'Link name — English'} onChange={e=>updateLink(i,j,{label:e.target.value})}/><input dir="rtl" value={l.labelAr ?? ''} placeholder="اسم الرابط — العربية" onChange={e=>updateLink(i,j,{labelAr:e.target.value})}/><input value={l.href} placeholder="/info/contact" onChange={e=>updateLink(i,j,{href:e.target.value})}/><button className="admin-icon-btn danger" onClick={()=>updateGroup(i,{links:g.links.filter((_,k)=>k!==j)})}><Trash2 size={15}/></button></div>)}<button className="admin-btn admin-btn-ghost admin-btn-sm" onClick={()=>updateGroup(i,{links:[...g.links,{label:'',labelAr:'',href:'/'}]})}><Plus size={14}/> {t('Add link')}</button></div></div></article>)}</div>
    </section>
    <section className="admin-card"><div className="admin-card-heading"><div><h2>{t('Trust strip')}</h2><p className="admin-hint">The four service/value messages above the footer.</p></div></div>{data.trustItems.map((x,i)=><div className="admin-section-row" key={i}><select value={x.icon} onChange={e=>setData(d=>({...d,trustItems:d.trustItems.map((t,j)=>j===i?{...t,icon:e.target.value as any}:t)}))}><option value="pin">{t('Location')}</option><option value="globe">{t('Globe')}</option><option value="star">{t('Star')}</option><option value="badge">{t('Badge')}</option></select><input value={x.text} placeholder="English" onChange={e=>setData(d=>({...d,trustItems:d.trustItems.map((t,j)=>j===i?{...t,text:e.target.value}:t)}))}/><input dir="rtl" value={x.textAr ?? ''} placeholder="العربية" onChange={e=>setData(d=>({...d,trustItems:d.trustItems.map((t,j)=>j===i?{...t,textAr:e.target.value}:t)}))}/><label className="admin-check"><input type="checkbox" checked={x.active} onChange={e=>setData(d=>({...d,trustItems:d.trustItems.map((t,j)=>j===i?{...t,active:e.target.checked}:t)}))}/> {t('Active')}</label></div>)}</section>
    <section className="admin-card"><div className="admin-card-heading"><div><h2>{t('Newsletter & footer details')}</h2></div></div><div className="admin-form-grid"><Field label={language === 'ar' ? 'عنوان النشرة — English' : 'Newsletter eyebrow — English'}><input value={data.newsletter.eyebrow} onChange={e=>setData(d=>({...d,newsletter:{...d.newsletter,eyebrow:e.target.value}}))}/></Field><Field label={language === 'ar' ? 'عنوان النشرة — العربية' : 'Newsletter eyebrow — Arabic'}><input dir="rtl" value={data.newsletter.eyebrowAr ?? ''} onChange={e=>setData(d=>({...d,newsletter:{...d.newsletter,eyebrowAr:e.target.value}}))}/></Field><Field label={t('Newsletter title')}><input value={data.newsletter.title} onChange={e=>setData(d=>({...d,newsletter:{...d.newsletter,title:e.target.value}}))}/></Field><Field label={language === 'ar' ? 'عنوان الاشتراك — العربية' : 'Newsletter title — Arabic'}><input dir="rtl" value={data.newsletter.titleAr ?? ''} onChange={e=>setData(d=>({...d,newsletter:{...d.newsletter,titleAr:e.target.value}}))}/></Field><Field label={t('Newsletter description')}><textarea value={data.newsletter.description} onChange={e=>setData(d=>({...d,newsletter:{...d.newsletter,description:e.target.value}}))}/></Field><Field label={language === 'ar' ? 'وصف الاشتراك — العربية' : 'Newsletter description — Arabic'}><textarea dir="rtl" value={data.newsletter.descriptionAr ?? ''} onChange={e=>setData(d=>({...d,newsletter:{...d.newsletter,descriptionAr:e.target.value}}))}/></Field><Field label={t('Newsletter image')}><input value={data.newsletter.image} onChange={e=>setData(d=>({...d,newsletter:{...d.newsletter,image:e.target.value}}))}/></Field><label className="admin-check"><input type="checkbox" checked={data.newsletter.active} onChange={e=>setData(d=>({...d,newsletter:{...d.newsletter,active:e.target.checked}}))}/> {t('Newsletter active')}</label><Field label={t('Demo disclaimer')}><textarea value={data.demoDisclaimer} onChange={e=>setData(d=>({...d,demoDisclaimer:e.target.value}))}/></Field><Field label={language === 'ar' ? 'تنبيه تجريبي — العربية' : 'Demo disclaimer — Arabic'}><textarea dir="rtl" value={data.demoDisclaimerAr ?? ''} onChange={e=>setData(d=>({...d,demoDisclaimerAr:e.target.value}))}/></Field></div></section>
    <div className="admin-modal-actions"><button className="admin-btn admin-btn-primary" onClick={save} disabled={saving}>{saving?<LoaderCircle size={15} className="spin"/>:<Save size={15}/>} Save footer</button></div>
  </>;
}
