'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { LoaderCircle, Plus, Save, Trash2 } from 'lucide-react';
import { api, Modal, useFlash } from './ui';
import { useLanguage } from '@/components/language-provider';
import { orderT } from '@/lib/i18n';

type CatalogRow = { variantId: number; productId: string; productName: string; color: string; stock: number; priceCents: number; salePriceIqd: number; image: string | null; published: boolean };
type ManualLine = CatalogRow & { quantity: number; unitPrice: number };

export function ManualOrderModal({ catalog, onClose }: { catalog: CatalogRow[]; onClose: () => void }) {
  const { language } = useLanguage(); const tr = (label: keyof typeof import('@/lib/i18n').orderTranslations) => orderT(label, language);
  const router = useRouter();
  const [name,setName]=useState(''),[phone,setPhone]=useState(''),[governorate,setGovernorate]=useState('baghdad'),[city,setCity]=useState(''),[address,setAddress]=useState(''),[landmark,setLandmark]=useState('');
  const [source,setSource]=useState('instagram'),[sourceNote,setSourceNote]=useState(''),[paymentMethod,setPaymentMethod]=useState('cod'),[paymentStatus,setPaymentStatus]=useState('unpaid'),[shipping,setShipping]=useState(''),[discount,setDiscount]=useState('0'),[note,setNote]=useState(''),[selected,setSelected]=useState('');
  const [lines,setLines]=useState<ManualLine[]>([]),[busy,setBusy]=useState(false); const {flash,fail}=useFlash();
  const addLine=()=>{const row=catalog.find(x=>x.variantId===Number(selected));if(!row||lines.some(x=>x.variantId===row.variantId))return;setLines(v=>[...v,{...row,quantity:1,unitPrice:row.salePriceIqd}]);setSelected('');};
  const subtotal=lines.reduce((s,x)=>s+x.unitPrice*x.quantity,0), safeDiscount=Math.min(Math.max(0,Number(discount)||0),subtotal), delivery=shipping===''?null:Math.max(0,Number(shipping)||0), total=Math.max(0,subtotal-safeDiscount)+(delivery??0);
  async function submit(){setBusy(true);try{const data=await api<{id:number}>('/api/admin/orders/manual',{method:'POST',json:{name,phone,governorate,city,address,landmark,source,sourceNote,paymentMethod,paymentStatus,shipping:delivery,discount:safeDiscount,note,items:lines.map(x=>({variantId:x.variantId,quantity:x.quantity,unitPrice:x.unitPrice}))}});router.push(`/admin/orders/${data.id}`);}catch(e){fail(e);setBusy(false);}}
  return <Modal title={tr('Add manual order')} onClose={onClose} wide>{flash}<div className="admin-form-grid">
    <label className="admin-field"><span>{tr('Customer name *')}</span><input value={name} onChange={e=>setName(e.target.value)} /></label><label className="admin-field"><span>{tr('Phone *')}</span><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="0770 123 4567" /></label>
    <label className="admin-field"><span>{tr('Order source *')}</span><select value={source} onChange={e=>setSource(e.target.value)}><option value="instagram">{tr('Instagram')}</option><option value="whatsapp">{tr('WhatsApp')}</option><option value="facebook">{tr('Facebook')}</option><option value="phone">{tr('Phone')}</option><option value="store">{tr('Store')}</option><option value="other">{tr('Other')}</option></select></label><label className="admin-field"><span>{tr('Source note')}</span><input value={sourceNote} onChange={e=>setSourceNote(e.target.value)} placeholder="DM / username / campaign" /></label>
    <label className="admin-field"><span>{tr('Governorate *')}</span><select value={governorate} onChange={e=>setGovernorate(e.target.value)}>{['baghdad','basra','nineveh','erbil','sulaymaniyah','duhok','kirkuk','anbar','babil','karbala','najaf','qadisiyah','muthanna','dhi-qar','maysan','wasit','diyala','saladin'].map(x=><option key={x} value={x}>{x}</option>)}</select></label><label className="admin-field"><span>{tr('City / district *')}</span><input value={city} onChange={e=>setCity(e.target.value)} /></label>
    <label className="admin-field admin-field-full"><span>{tr('Detailed address *')}</span><input value={address} onChange={e=>setAddress(e.target.value)} /></label><label className="admin-field"><span>{tr('Landmark')}</span><input value={landmark} onChange={e=>setLandmark(e.target.value)} /></label>
  </div>
  <section className="admin-card" style={{marginTop:18}}><div className="admin-card-heading"><h3>{tr('Products')}</h3></div><div className="admin-toolbar admin-product-picker"><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">{tr('Choose product / color…')}</option>{catalog.filter(x=>x.published&&x.stock>0).map(x=><option key={x.variantId} value={x.variantId}>{x.productName} · {x.color} · stock {x.stock}</option>)}</select><button type="button" className="admin-btn admin-btn-primary" onClick={addLine} disabled={!selected}><Plus size={15}/>{tr('Add product')}</button></div>{selected && (()=>{const picked=catalog.find(x=>x.variantId===Number(selected)); return picked ? <div className="admin-selected-product"><img src={picked.image || '/placeholder.svg'} alt=""/><div><strong>{picked.productName}</strong><span>{picked.color} · {picked.stock} {tr('Stock')} · {picked.salePriceIqd.toLocaleString()} IQD</span></div></div> : null;})()}{lines.length>0&&<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>{tr('Product')}</th><th>{tr('Qty')}</th><th>{tr('Sale / unit')}</th><th>{tr('Total')}</th><th/></tr></thead><tbody>{lines.map((line,i)=><tr key={line.variantId}><td><div className="admin-product-cell"><img src={line.image || '/placeholder.svg'} alt=""/><div><strong>{line.productName}</strong><small>{line.color} · {tr('Stock')} {line.stock}</small></div></div></td><td><input type="number" min="1" max={line.stock} value={line.quantity} onChange={e=>setLines(v=>v.map((x,j)=>j===i?{...x,quantity:Math.max(1,Math.min(x.stock,Number(e.target.value)||1))}:x))} style={{width:80}}/></td><td><input type="number" min="0" step="250" value={line.unitPrice} onChange={e=>setLines(v=>v.map((x,j)=>j===i?{...x,unitPrice:Math.max(0,Number(e.target.value)||0)}:x))} style={{width:120}}/></td><td>{(line.unitPrice*line.quantity).toLocaleString()} IQD</td><td><button type="button" className="admin-icon-btn" onClick={()=>setLines(v=>v.filter((_,j)=>j!==i))}><Trash2 size={15}/></button></td></tr>)}</tbody></table></div>}</section>
  <div className="admin-form-grid" style={{marginTop:18}}><label className="admin-field"><span>{tr('Delivery')}</span><input type="number" min="0" step="500" value={shipping} onChange={e=>setShipping(e.target.value)} placeholder="Default by governorate"/></label><label className="admin-field"><span>{tr('Discount')}</span><input type="number" min="0" step="250" value={discount} onChange={e=>setDiscount(e.target.value)}/></label><label className="admin-field"><span>{tr('Payment')}</span><select value={paymentMethod} onChange={e=>setPaymentMethod(e.target.value)}><option value="cod">{tr('Cash on delivery')}</option><option value="cash">{tr('Cash')}</option><option value="bank_transfer">{tr('Bank transfer')}</option><option value="electronic">{tr('Electronic')}</option></select></label><label className="admin-field"><span>{tr('Payment status')}</span><select value={paymentStatus} onChange={e=>setPaymentStatus(e.target.value)}><option value="unpaid">{tr('Unpaid')}</option><option value="paid">{tr('Paid')}</option></select></label><label className="admin-field admin-field-full"><span>{tr('Customer note')}</span><textarea value={note} onChange={e=>setNote(e.target.value)} rows={3}/></label></div>
  <div className="admin-alert info" style={{marginTop:16}}><strong>Products: {subtotal.toLocaleString()} IQD</strong> · الربح يُحسب تلقائياً من (سعر البيع − سعر الشراء) لكل قطعة · Delivery: {delivery===null?'default':`${delivery.toLocaleString()} IQD`} · Total: {total.toLocaleString()} IQD</div><div className="admin-modal-actions"><button className="admin-btn admin-btn-ghost" onClick={onClose}>{tr('Cancel')}</button><button className="admin-btn admin-btn-primary" disabled={busy||!name||!phone||!city||!address||!lines.length} onClick={()=>void submit()}>{busy?<LoaderCircle size={15} className="spin"/>:<Save size={15}/>} Create order</button></div></Modal>;
}
