'use client';
import { useMemo, useRef, useState } from 'react';
import { Copy, Image as ImageIcon, Search, Trash2, Upload, X } from 'lucide-react';
import { useLanguage } from '@/components/language-provider';
import { batchT } from '@/lib/i18n';

type Item = { id:number; filename:string; mimeType:string; size:number; createdAt:string };
const fmtSize = (n:number) => n < 1024 ? `${n} B` : n < 1024*1024 ? `${(n/1024).toFixed(1)} KB` : `${(n/1024/1024).toFixed(1)} MB`;
export function MediaLibrary({ initialItems }:{ initialItems:Item[] }) {
  const { language } = useLanguage(); const t=(x:string)=>batchT(x,language);
  const [items,setItems] = useState(initialItems); const [query,setQuery] = useState(''); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(''); const input=useRef<HTMLInputElement>(null);
  const visible=useMemo(()=>items.filter(x=>x.filename.toLowerCase().includes(query.trim().toLowerCase())),[items,query]);
  async function upload(files:FileList|null){ if(!files?.length)return; setBusy(true); setMessage(''); try { const form=new FormData(); Array.from(files).slice(0,12).forEach(f=>form.append('files',f)); const r=await fetch('/api/admin/media',{method:'POST',body:form}); const data=await r.json(); if(!r.ok) throw new Error(data.error||'Upload failed'); const fresh=await fetch('/api/admin/media').then(x=>x.json()); setItems(fresh.items); setMessage(`${data.urls.length} image${data.urls.length===1?'':'s'} uploaded.`); } catch(e){setMessage(e instanceof Error?e.message:'Upload failed.');} finally{setBusy(false); if(input.current) input.current.value='';} }
  async function remove(item:Item){ if(!confirm(`Delete “${item.filename}”? If it is used on the storefront, deletion will be blocked.`))return; setBusy(true); setMessage(''); try{const r=await fetch(`/api/admin/media?id=${item.id}`,{method:'DELETE'}); const data=await r.json(); if(!r.ok)throw new Error(data.error||'Delete failed'); setItems(x=>x.filter(i=>i.id!==item.id)); setMessage(t('Image deleted.'));}catch(e){setMessage(e instanceof Error?e.message:'Delete failed.');}finally{setBusy(false);} }
  async function copy(item:Item){ await navigator.clipboard?.writeText(`/api/media/${item.id}`); setMessage(t('Media URL copied.')); }
  return <section className="admin-card media-library"><div className="media-toolbar"><div className="media-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t('Search images...')}/></div><input ref={input} type="file" accept="image/*" multiple hidden onChange={e=>upload(e.target.files)}/><button className="button button-dark" onClick={()=>input.current?.click()} disabled={busy}><Upload size={16}/>{busy?t('Working...'):t('Upload images')}</button></div>{message&&<div className="admin-inline-message">{message}</div>}{visible.length===0?<div className="media-empty"><ImageIcon size={34}/><h2>{query?t('No matching images'):t('No media yet')}</h2><p>Upload JPG, PNG, WebP or AVIF images to build your reusable media library.</p></div>:<div className="media-grid">{visible.map(item=><article className="media-card" key={item.id}><div className="media-preview"><img src={`/api/media/${item.id}`} alt={item.filename}/></div><div className="media-card-body"><strong title={item.filename}>{item.filename}</strong><small>{fmtSize(item.size)} · {item.createdAt.slice(0, 10)}</small><div className="media-actions"><button onClick={()=>copy(item)} title={t('Copy URL')}><Copy size={15}/></button><button onClick={()=>remove(item)} title={t('Delete')}><Trash2 size={15}/></button></div></div></article>)}</div>}{query&&<button className="media-clear" onClick={()=>setQuery('')}><X size={14}/> {t('Clear search')}</button>}</section>;
}
