'use client';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, Banknote, Clock, LoaderCircle, MapPin, Phone, Printer, Save, Search, Truck, Plus, Pencil, Trash2 } from 'lucide-react';
import { orderStatuses, statusLabels, statusTransitions, type OrderStatus } from '@/lib/iraq';
import { api, money, Modal, StatusBadge, useFlash, when } from './ui';
import { ManualOrderModal } from './manual-order-modal';
import { useLanguage } from '@/components/language-provider';
import { orderStatusT, orderT } from '@/lib/i18n';

export type OrderRow = { id: number; reference: string; name: string; phone: string; email: string; governorate: string; status: string; paymentStatus: string; paymentMethod: string; currency: string; totalCents: number; subtotalCents: number; shippingCents: number; discountCents: number; codFeeCents: number; couponCode: string | null; createdAt: string; updatedAt: string; items: { productId: string; variantId: number; name: string; color: string; quantity: number; unitPrice?: number; profitIqd?: number | null; priceCents?: number; purchaseCostCents?: number | null; batchAllocations?: { batchId: number; quantity: number }[]; image?: string | null }[]; address: { governorate?: string; governorateAr?: string; city?: string; line1?: string; line2?: string; landmark?: string; altPhone?: string; country?: string; postalCode?: string }; customerNote: string | null; adminNote: string | null; trackingNumber: string | null; courier: string | null; source: string; sourceNote: string | null };
export type OrderEvent = { id: number; type: string; message: string; createdAt: string };
type CatalogRow = { variantId: number; productId: string; productName: string; color: string; stock: number; priceCents: number; salePriceIqd: number; image: string | null; published: boolean };

function EditOrderModal({ order, catalog, onClose }: { order: OrderRow; catalog: CatalogRow[]; onClose: () => void }) {
  const { language } = useLanguage(); const tr = (label: keyof typeof import('@/lib/i18n').orderTranslations) => orderT(label, language);
  const router = useRouter();
  const [name,setName]=useState(order.name),[phone,setPhone]=useState(order.phone),[email,setEmail]=useState(order.email);
  const [governorate,setGovernorate]=useState(order.governorate || 'baghdad'),[city,setCity]=useState(order.address?.city || ''),[address,setAddress]=useState(order.address?.line1 || ''),[landmark,setLandmark]=useState(order.address?.landmark || '');
  const [source,setSource]=useState(order.source || 'website'),[sourceNote,setSourceNote]=useState(order.sourceNote || ''),[shipping,setShipping]=useState(String(order.shippingCents || '')),[discount,setDiscount]=useState(String(order.discountCents || '')),[paymentMethod,setPaymentMethod]=useState(order.paymentMethod),[paymentStatus,setPaymentStatus]=useState(order.paymentStatus),[note,setNote]=useState(order.customerNote || '');
  const [items,setItems]=useState(order.items.map(item => ({ variantId:item.variantId, quantity:item.quantity, unitPrice:item.unitPrice ?? item.priceCents ?? 0 })));
  const [busy,setBusy]=useState(false); const {flash,fail}=useFlash();
  async function submit(){setBusy(true);try{const data=await api<{order:OrderRow}>(`/api/admin/orders/${order.id}`,{method:'PATCH',json:{name,phone,email,governorate,city,address,landmark,source,sourceNote,shipping:Number(shipping)||0,discount:Number(discount)||0,paymentMethod,paymentStatus,customerNote:note,items}});onClose();window.dispatchEvent(new CustomEvent('admin-order-updated',{detail:data.order}));}catch(e){fail(e);setBusy(false);}}
  function addItem(){ const first=catalog.find(c=>c.stock>0 && !items.some(i=>i.variantId===c.variantId)); if(first) setItems([...items,{variantId:first.variantId,quantity:1,unitPrice:first.salePriceIqd}]); }
  function updateItem(index:number,key:'variantId'|'quantity'|'unitPrice',value:number){ setItems(items.map((item,i)=>i===index?{...item,[key]:value}:item)); }
  function removeItem(index:number){ if(items.length>1) setItems(items.filter((_,i)=>i!==index)); }
  return <Modal title={`Edit order ${order.reference}`} onClose={onClose} wide>{flash}<div className="admin-form-grid">
    <label className="admin-field"><span>{tr('Customer name *')}</span><input value={name} onChange={e=>setName(e.target.value)} /></label><label className="admin-field"><span>{tr('Phone *')}</span><input value={phone} onChange={e=>setPhone(e.target.value)} /></label>
    <label className="admin-field"><span>{tr('Email')}</span><input value={email} onChange={e=>setEmail(e.target.value)} /></label><label className="admin-field"><span>{tr('Order source')}</span><select value={source} onChange={e=>setSource(e.target.value)}><option value="website">{tr('Website')}</option><option value="instagram">{tr('Instagram')}</option><option value="whatsapp">{tr('WhatsApp')}</option><option value="facebook">{tr('Facebook')}</option><option value="phone">{tr('Phone')}</option><option value="store">{tr('Store')}</option><option value="other">{tr('Other')}</option></select></label>
    <label className="admin-field"><span>{tr('Source note')}</span><input value={sourceNote} onChange={e=>setSourceNote(e.target.value)} /></label><label className="admin-field"><span>{tr('Governorate *')}</span><select value={governorate} onChange={e=>setGovernorate(e.target.value)}>{['baghdad','basra','nineveh','erbil','sulaymaniyah','duhok','kirkuk','anbar','babil','karbala','najaf','qadisiyah','muthanna','dhi-qar','maysan','wasit','diyala','saladin'].map(x=><option key={x} value={x}>{x}</option>)}</select></label>
    <label className="admin-field"><span>{tr('City / district *')}</span><input value={city} onChange={e=>setCity(e.target.value)} /></label><label className="admin-field"><span>{tr('Landmark')}</span><input value={landmark} onChange={e=>setLandmark(e.target.value)} /></label>
    <label className="admin-field admin-field-full"><span>{tr('Detailed address *')}</span><input value={address} onChange={e=>setAddress(e.target.value)} /></label>
    <label className="admin-field"><span>{tr('Delivery')}</span><input type="number" min="0" step="500" value={shipping} onChange={e=>setShipping(e.target.value)} /></label><label className="admin-field"><span>{tr('Discount')}</span><input type="number" min="0" step="250" value={discount} onChange={e=>setDiscount(e.target.value)} /></label>
    <label className="admin-field"><span>{tr('Payment')}</span><select value={paymentMethod} onChange={e=>setPaymentMethod(e.target.value)}><option value="cod">{tr('Cash on delivery')}</option><option value="cash">{tr('Cash')}</option><option value="bank_transfer">{tr('Bank transfer')}</option><option value="electronic">{tr('Electronic')}</option></select></label><label className="admin-field"><span>{tr('Payment status')}</span><select value={paymentStatus} onChange={e=>setPaymentStatus(e.target.value)}><option value="unpaid">{tr('Unpaid')}</option><option value="paid">{tr('Paid')}</option><option value="refunded">{tr('Refunded')}</option></select></label>
    <label className="admin-field admin-field-full"><span>{tr('Customer note')}</span><textarea value={note} onChange={e=>setNote(e.target.value)} rows={3}/></label>
  </div>
  <div className="admin-card" style={{marginTop:16,padding:16}}><div className="admin-card-heading"><h2>{tr('Edit products')}</h2><button type="button" className="admin-btn admin-btn-ghost admin-btn-sm" onClick={addItem}><Plus size={13}/> {tr('Add product')}</button></div>{items.map((item,index)=>{const selected=catalog.find(c=>c.variantId===item.variantId);return <div key={`${item.variantId}-${index}`} className="admin-form-grid" style={{marginTop:12,alignItems:'end'}}><label className="admin-field"><span>{tr('Product / color')}</span><div style={{display:'flex',gap:10,alignItems:'center'}}>{selected?.image && <img src={selected.image} alt="" style={{width:44,height:44,objectFit:'cover',borderRadius:8}}/>}<select value={item.variantId} onChange={e=>{const v=catalog.find(c=>c.variantId===Number(e.target.value));setItems(items.map((x,i)=>i===index?{...x,variantId:Number(e.target.value),unitPrice:v?.salePriceIqd ?? x.unitPrice}:x));}}>{catalog.map(c=><option key={c.variantId} value={c.variantId}>{c.productName} — {c.color} · {c.stock} in stock</option>)}</select></div></label><label className="admin-field"><span>{tr('Quantity')}</span><input type="number" min="1" value={item.quantity} onChange={e=>updateItem(index,'quantity',Math.max(1,Number(e.target.value)||1))}/></label><label className="admin-field"><span>{tr('Sale / unit (IQD)')}</span><input type="number" min="0" step="500" value={item.unitPrice} onChange={e=>updateItem(index,'unitPrice',Math.max(0,Number(e.target.value)||0))}/></label><button type="button" className="admin-btn admin-btn-danger-ghost admin-btn-sm" onClick={()=>removeItem(index)} disabled={items.length===1}><Trash2 size={13}/>{tr('Remove')}</button></div>})}</div><div className="admin-alert info" style={{marginTop:16}}>Changing products will update stock using the current inventory batches and will keep the sale price used on this order.</div><div className="admin-modal-actions"><button className="admin-btn admin-btn-ghost" onClick={onClose}>{tr('Cancel')}</button><button className="admin-btn admin-btn-primary" disabled={busy||!name||!phone||!city||!address} onClick={()=>void submit()}>{busy?<LoaderCircle size={15} className="spin"/>:<Save size={15}/>} Save changes</button></div></Modal>;
}

export function OrdersTable({ rows, catalog }: { rows: OrderRow[]; catalog: CatalogRow[] }) {
  const { language } = useLanguage(); const tr = (label: keyof typeof import('@/lib/i18n').orderTranslations) => orderT(label, language);
  const [localRows, setLocalRows] = useState(rows);
  useEffect(() => setLocalRows(rows), [rows]);
  const [manualOpen, setManualOpen] = useState(false), [editOrder, setEditOrder] = useState<OrderRow | null>(null);
  useEffect(() => { const handler=(event:Event)=>{ const order=(event as CustomEvent<OrderRow>).detail; if(order?.id) setLocalRows(current=>current.map(item=>item.id===order.id?order:item)); }; window.addEventListener('admin-order-updated',handler); return ()=>window.removeEventListener('admin-order-updated',handler); }, []);
  const [query, setQuery] = useState(''), [status, setStatus] = useState('all'), [busyId, setBusyId] = useState<number | null>(null);
  const visible = useMemo(() => localRows.filter(row => (status === 'all' || row.status === status) && (!query || `${row.reference} ${row.name} ${row.phone} ${row.email} ${row.governorate} ${row.address?.city ?? ''}`.toLowerCase().includes(query.toLowerCase()))), [localRows, query, status]);
  const counts = useMemo(() => Object.fromEntries(orderStatuses.map(item => [item, localRows.filter(row => row.status === item).length])), [localRows]);
  async function advance(row: OrderRow) { const current = (orderStatuses.includes(row.status as OrderStatus) ? row.status : 'pending') as OrderStatus; const next = statusTransitions[current].find(x => x !== 'cancelled' && x !== 'returned'); if (!next) return; setBusyId(row.id); try { const data=await api<{order:OrderRow}>(`/api/admin/orders/${row.id}`, { method:'PATCH', json:{status:next} }); setLocalRows(current=>current.map(item=>item.id===row.id?data.order:item)); } catch (e) { window.alert(e instanceof Error ? e.message : 'Could not update status.'); } finally { setBusyId(null); } }
  async function remove(row: OrderRow) { if (!confirm(`${tr('Delete order')} ${row.reference}? ${tr('Stock')} will be returned automatically if the order is still active.`)) return; setBusyId(row.id); try { await api(`/api/admin/orders/${row.id}`, { method:'DELETE' }); setLocalRows(current=>current.filter(item=>item.id!==row.id)); } catch (e) { window.alert(e instanceof Error ? e.message : 'Could not delete order.'); } finally { setBusyId(null); } }
  return <>{manualOpen && <ManualOrderModal catalog={catalog} onClose={() => setManualOpen(false)} />}{editOrder && <EditOrderModal order={editOrder} catalog={catalog} onClose={() => setEditOrder(null)} />}<section className="admin-card"><div className="admin-toolbar"><button className="admin-btn admin-btn-primary" onClick={() => setManualOpen(true)}><Plus size={15}/>{tr('Add manual order')}</button><label className="admin-search"><Search size={16} /><input placeholder="Search reference, name, phone, city…" value={query} onChange={event => setQuery(event.target.value)} aria-label="Search orders" /></label><div className="admin-segmented admin-segmented-scroll" role="tablist"><button role="tab" aria-selected={status === 'all'} className={status === 'all' ? 'active' : ''} onClick={() => setStatus('all')}>All ({rows.length})</button>{orderStatuses.map(item => <button key={item} role="tab" aria-selected={status === item} className={status === item ? 'active' : ''} onClick={() => setStatus(item)}>{orderStatusT(item, language)} ({counts[item]})</button>)}</div></div>
    <div className="admin-table-wrap"><table className="admin-table admin-orders-table"><thead><tr><th>{tr('Order')}</th><th>{tr('Customer')}</th><th>{tr('Delivery')}</th><th>{tr('Items')}</th><th className="num">{tr('Total')}</th><th>{tr('Payment')}</th><th>{tr('Status')}</th><th>{tr('Actions')}</th></tr></thead><tbody>{visible.map(row => { const current=(orderStatuses.includes(row.status as OrderStatus)?row.status:'pending') as OrderStatus; const next=statusTransitions[current].find(x=>x!=='cancelled'&&x!=='returned'); const busy=busyId===row.id; return <tr key={row.id}><td><Link href={`/admin/orders/${row.id}`} className="admin-strong-link">{row.reference}</Link><br /><small>{when(row.createdAt)} · {row.source === 'website' ? 'Website' : row.source}</small></td><td>{row.name}<br /><small><Phone size={10} /> {row.phone || row.email}</small></td><td>{row.address?.governorate || row.governorate || '—'}<br /><small>{row.address?.city}</small></td><td>{row.items.reduce((sum, item) => sum + item.quantity, 0)} item{row.items.length === 1 ? '' : 's'}<br /><small>{row.items.slice(0, 2).map(item => item.name).join(', ')}{row.items.length > 2 ? '…' : ''}</small></td><td className="num"><strong>{money(row.totalCents, row.currency)}</strong>{row.discountCents > 0 && <><br /><small>−{money(row.discountCents, row.currency)} {row.couponCode}</small></>}</td><td><StatusBadge status={row.paymentStatus} /><br /><small>{row.paymentMethod === 'cod' ? tr('Cash on delivery') : row.paymentMethod}</small></td><td><StatusBadge status={row.status} /></td><td><div className="admin-order-actions"><button className="admin-btn admin-btn-ghost admin-btn-sm" title={`${tr('Edit')} ${row.reference}`} onClick={()=>setEditOrder(row)} disabled={busy}><Pencil size={13}/>{tr('Edit')}</button>{next && <button className="admin-btn admin-btn-primary admin-btn-sm" title={`Move to ${orderStatusT(next, language)}`} onClick={()=>void advance(row)} disabled={busy}>{busy ? <LoaderCircle size={13} className="spin"/> : <ArrowRight size={13}/>} {busy ? tr('Saving…') : `→ ${orderStatusT(next, language)}`}</button>}<button className="admin-btn admin-btn-danger-ghost admin-btn-sm" title={tr('Delete order')} onClick={()=>void remove(row)} disabled={busy}><Trash2 size={13}/>{tr('Delete')}</button><Link href={`/admin/orders/${row.id}`} className="admin-btn admin-btn-ghost admin-btn-sm">{tr('Manage')} <ArrowRight size={13} /></Link></div></td></tr>; })}{!visible.length && <tr><td colSpan={8}><p className="admin-empty">{tr('No orders match that filter.')}</p></td></tr>}</tbody></table></div></section></>;
}

export function OrderDetail({ initial, events: initialEvents }: { initial: OrderRow; events: OrderEvent[] }) {
  const { language } = useLanguage(); const tr = (label: keyof typeof import('@/lib/i18n').orderTranslations) => orderT(label, language);
  const router = useRouter();
  const [order, setOrder] = useState(initial);
  const [events, setEvents] = useState(initialEvents);
  const [tracking, setTracking] = useState(order.trackingNumber ?? '');
  const [courier, setCourier] = useState(order.courier ?? '');
  const [note, setNote] = useState(order.adminNote ?? '');
  const [busy, setBusy] = useState<string | null>(null);
  const { flash, success, fail } = useFlash();
  const current = (orderStatuses.includes(order.status as OrderStatus) ? order.status : 'pending') as OrderStatus;
  const nextStatuses = statusTransitions[current];
  async function patch(body: Record<string, unknown>, label: string) {
    setBusy(label);
    try { const data = await api<{ order: OrderRow; events: OrderEvent[] }>(`/api/admin/orders/${order.id}`, { method: 'PATCH', json: body }); setOrder(data.order); setEvents(data.events); success(`${label} saved.`); router.refresh(); }
    catch (error) { fail(error); }
    finally { setBusy(null); }
  }
  const steps: OrderStatus[] = ['pending', 'confirmed', 'processing', 'shipped', 'delivered'];
  const stepIndex = steps.indexOf(current);
  const address = order.address ?? {};
  return <main className="admin-page"><div className="admin-page-heading"><div><Link href="/admin/orders" className="admin-link">← {tr('All orders')}</Link><h1>{tr('Order')} {order.reference}</h1><p>{tr('Source')}: {order.source === 'website' ? 'Website' : order.source} · {tr('Placed')} {when(order.createdAt)} · {order.paymentMethod === 'cod' ? tr('Cash on delivery') : order.paymentMethod} · <StatusBadge status={order.status} /> <StatusBadge status={order.paymentStatus} /></p></div><div className="admin-heading-actions"><button className="admin-btn admin-btn-ghost" onClick={() => window.print()}><Printer size={15} />{tr('Print packing slip')}</button></div></div>{flash}
    {current !== 'cancelled' && current !== 'returned' ? <ol className="admin-steps">{steps.map((step, index) => { const canMoveTo = statusTransitions[current].includes(step); const isCurrent = index === stepIndex; const isBusy = busy === `Status ${statusLabels[step]}`; return <li key={step} className={index < stepIndex ? 'done' : isCurrent ? 'current' : ''}><button type="button" className="admin-step-button" disabled={!canMoveTo || busy !== null} title={canMoveTo ? `Move to ${statusLabels[step]}` : isCurrent ? 'Current status' : 'This status is not available from the current stage'} onClick={() => canMoveTo && void patch({ status: step, trackingNumber: tracking, courier }, `Status ${statusLabels[step]}`)}><i>{isBusy ? '…' : index + 1}</i><span>{statusLabels[step]}</span></button></li>; })}</ol> : <div className={`admin-alert ${current === 'cancelled' ? 'error' : 'info'}`}>This order was {current}. Stock for every item has been returned to inventory.</div>}
    <div className="admin-grid-order">
      <div>
        <section className="admin-card"><div className="admin-card-heading"><h2>{tr('Items')}</h2><span className="admin-count">{order.items.reduce((sum, item) => sum + item.quantity, 0)} {tr('units')}</span></div><table className="admin-table"><thead><tr><th>{tr('Product')}</th><th>{tr('Color')}</th><th className="num">{tr('Qty')}</th><th className="num">{tr('Sale / unit')}</th><th className="num">{tr('Cost')}</th><th className="num">{tr('Line profit')}</th></tr></thead><tbody>{order.items.map((item, index) => { const unit = item.unitPrice ?? item.priceCents ?? 0; const cost = item.purchaseCostCents; const grossOrder = order.items.reduce((sum, row) => sum + (row.unitPrice ?? row.priceCents ?? 0) * row.quantity, 0); const safeDiscount = Math.min(Math.max(0, order.discountCents || 0), grossOrder); const grossLine = unit * item.quantity; const netLine = grossOrder > 0 ? Math.max(0, grossLine - safeDiscount * (grossLine / grossOrder)) : 0; const lineProfit = cost == null ? null : netLine - cost * item.quantity; return <tr key={index}><td><div className="admin-product-cell">{item.image && <img src={item.image} alt="" />}<div><Link href={`/admin/products/${item.productId}`} className="admin-strong-link">{item.name}</Link><small>/{item.productId}</small></div></div></td><td>{item.color}</td><td className="num">{item.quantity}</td><td className="num">{money(unit, order.currency)}</td><td className="num">{cost == null ? 'Unknown' : money(cost, order.currency)}</td><td className="num">{lineProfit == null ? '—' : money(lineProfit, order.currency)}</td></tr>; })}</tbody><tfoot><tr><td colSpan={5} className="num">{tr('Subtotal')}</td><td className="num">{money(order.subtotalCents, order.currency)}</td></tr>{order.discountCents > 0 && <tr><td colSpan={5} className="num">Discount {order.couponCode && <small>({order.couponCode})</small>}</td><td className="num">− {money(order.discountCents, order.currency)}</td></tr>}<tr><td colSpan={5} className="num">{tr('Delivery')}</td><td className="num">{order.shippingCents ? money(order.shippingCents, order.currency) : 'Free'}</td></tr>{order.codFeeCents > 0 && <tr><td colSpan={5} className="num">{tr('Cash handling')}</td><td className="num">{money(order.codFeeCents, order.currency)}</td></tr>}<tr className="admin-total-row"><td colSpan={5} className="num">{tr('Total to collect')}</td><td className="num">{money(order.totalCents, order.currency)}</td></tr></tfoot></table></section>
        <section className="admin-card"><div className="admin-card-heading"><h2><Clock size={16} />{tr('Timeline')}</h2></div><ol className="admin-timeline">{events.map(event => <li key={event.id}><span>{when(event.createdAt)}</span><strong>{event.type}</strong><p>{event.message}</p></li>)}</ol></section>
      </div>
      <div>
        <section className="admin-card"><div className="admin-card-heading"><h2><Truck size={16} />{tr('Fulfilment')}</h2></div>{nextStatuses.length > 0 && <div className="admin-status-actions"><div className="admin-next-status"><span>{tr('Current')}: <strong>{orderStatusT(current, language)}</strong></span>{nextStatuses.filter(x => x !== 'cancelled' && x !== 'returned')[0] && <button className="admin-btn admin-btn-primary" disabled={busy !== null} onClick={() => { const next = nextStatuses.find(x => x !== 'cancelled' && x !== 'returned')!; void patch({ status: next, trackingNumber: tracking, courier }, `Status ${orderStatusT(next, language)}`); }}>{busy === `Status ${statusLabels[nextStatuses.find(x => x !== 'cancelled' && x !== 'returned')!]}` ? <LoaderCircle size={15} className="spin" /> : <ArrowRight size={15} />} Advance to {statusLabels[nextStatuses.find(x => x !== 'cancelled' && x !== 'returned')!].toLowerCase()}</button>}</div><div className="admin-status-secondary">{nextStatuses.filter(x => x === 'cancelled' || x === 'returned').map(next => <button key={next} className="admin-btn admin-btn-danger-ghost admin-btn-sm" disabled={busy !== null} onClick={() => { if (!confirm(`Mark this order as ${next}? Stock will be returned to inventory.`)) return; void patch({ status: next, trackingNumber: tracking, courier }, `Status ${orderStatusT(next, language)}`); }}>Mark as {statusLabels[next].toLowerCase()}</button>)}</div></div>}
          <div className="admin-form-grid" style={{ marginTop: 16 }}><label className="admin-field"><span>{tr('Courier')}</span><input value={courier} onChange={event => setCourier(event.target.value)} placeholder="e.g. Al-Barid, Sandoog, in-house" /></label><label className="admin-field"><span>{tr('Tracking / waybill no.')}</span><input value={tracking} onChange={event => setTracking(event.target.value)} placeholder="Optional" /></label><label className="admin-field span-2"><span>{tr('Internal note')}</span><textarea rows={3} value={note} onChange={event => setNote(event.target.value)} placeholder="Only visible to staff" /></label></div><button className="admin-btn admin-btn-ghost" disabled={busy !== null} onClick={() => void patch({ trackingNumber: tracking, courier, adminNote: note }, 'Fulfilment details')}><Save size={14} /> Save details</button>
          <div className="admin-payment-row"><Banknote size={16} /><span>{tr('Payment')}: <StatusBadge status={order.paymentStatus} /></span>{order.paymentStatus !== 'paid' ? <button className="admin-btn admin-btn-ghost admin-btn-sm" disabled={busy !== null} onClick={() => void patch({ paymentStatus: 'paid' }, 'Payment')}>{tr('Mark as paid')}</button> : <button className="admin-btn admin-btn-ghost admin-btn-sm" disabled={busy !== null} onClick={() => void patch({ paymentStatus: 'refunded' }, 'Payment')}>{tr('Mark refunded')}</button>}</div></section>
        <section className="admin-card"><div className="admin-card-heading"><h2><MapPin size={16} /> Customer & delivery</h2></div><dl className="admin-dl"><dt>{tr('Name')}</dt><dd>{order.name}</dd><dt>{tr('Phone')}</dt><dd><a href={`tel:${order.phone}`}>{order.phone}</a>{address.altPhone && <> · <a href={`tel:${address.altPhone}`}>{address.altPhone}</a></>}<br /><a className="admin-link" href={`https://wa.me/964${order.phone.replace(/^0/, '')}`} target="_blank" rel="noreferrer">{tr('Message on WhatsApp')}</a></dd>{order.email && <><dt>{tr('Email')}</dt><dd>{order.email}</dd></>}<dt>Governorate</dt><dd>{address.governorate || order.governorate} {address.governorateAr && <small>· {address.governorateAr}</small>}</dd><dt>{tr('Address')}</dt><dd>{address.city && <>{address.city}<br /></>}{address.line1}{address.line2 && <><br />{address.line2}</>}{address.landmark && <><br /><small>Landmark: {address.landmark}</small></>}</dd>{order.customerNote && <><dt>{tr('Customer note')}</dt><dd>{order.customerNote}</dd></>}</dl><Link href={`/admin/customers?q=${encodeURIComponent(order.phone || order.email)}`} className="admin-link">Customer history <ArrowRight size={13} /></Link></section>
      </div>
    </div>
    <section className="admin-print-slip"><h2>{order.reference}</h2><p>{order.name} · {order.phone}</p><p>{address.governorate} · {address.city} · {address.line1} {address.landmark ? `· ${address.landmark}` : ''}</p><ul>{order.items.map((item, index) => <li key={index}>{item.quantity} × {item.name} — {item.color}</li>)}</ul><p><strong>{tr('Collect')}: {money(order.totalCents, order.currency)}</strong> ({tr('Cash on delivery')})</p></section>
  </main>;
}
