import { eq, desc, inArray } from 'drizzle-orm';
import { db } from '@/db';
import { inventoryMovements, inventoryBatches, productVariants } from '@/db/schema';
import { catalogT } from '@/lib/i18n';

export async function ProductMovementLedger({ productId, language='en' }: { productId:string; language?:'en'|'ar' }) {
  const variants = await db.select({id:productVariants.id,name:productVariants.name,stock:productVariants.stock}).from(productVariants).where(eq(productVariants.productId,productId));
  const ids = variants.map(v=>v.id);
  if (!ids.length) return <section className="admin-card"><div className="admin-card-heading"><h2>{catalogT('Material movement',language)}</h2></div><p className="admin-empty">{catalogT('No variants yet.',language)}</p></section>;
  const movements = await db.select({id:inventoryMovements.id,variantId:inventoryMovements.variantId,delta:inventoryMovements.delta,stockAfter:inventoryMovements.stockAfter,reason:inventoryMovements.reason,reference:inventoryMovements.reference,createdAt:inventoryMovements.createdAt}).from(inventoryMovements).where(inArray(inventoryMovements.variantId,ids)).orderBy(desc(inventoryMovements.createdAt)).limit(100);
  const batches = await db.select({variantId:inventoryBatches.variantId,batchNumber:inventoryBatches.batchNumber,quantityReceived:inventoryBatches.quantityReceived,quantityRemaining:inventoryBatches.quantityRemaining,purchaseCostIqd:inventoryBatches.purchaseCostIqd,receivedAt:inventoryBatches.receivedAt}).from(inventoryBatches).orderBy(desc(inventoryBatches.receivedAt)).limit(100);
  return <section className="admin-card"><div className="admin-card-heading"><div><h2>{catalogT('Material movement',language)}</h2><p>{catalogT('Every purchase, sale, return and adjustment is recorded by color/variant.',language)}</p></div></div><div className="admin-grid-2"><div><strong>{catalogT('Current stock',language)}</strong><div>{variants.reduce((s,v)=>s+v.stock,0).toLocaleString('en-US')}</div></div><div><strong>{catalogT('Inventory value',language)}</strong><div>{batches.reduce((s,b)=>s+(b.purchaseCostIqd==null?0:b.quantityRemaining*b.purchaseCostIqd),0).toLocaleString('en-US')} IQD</div></div></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>{catalogT('Date',language)}</th><th>{catalogT('Color',language)}</th><th>{catalogT('Movement',language)}</th><th className="num">{catalogT('Quantity',language)}</th><th className="num">{catalogT('Balance',language)}</th><th>{catalogT('Reference',language)}</th></tr></thead><tbody>{movements.map(m=><tr key={m.id}><td>{new Date(m.createdAt).toLocaleString('en-GB')}</td><td>{variants.find(v=>v.id===m.variantId)?.name ?? '—'}</td><td>{m.reason}</td><td className="num">{m.delta>0?'+':''}{m.delta}</td><td className="num">{m.stockAfter}</td><td>{m.reference ?? '—'}</td></tr>)}{!movements.length&&<tr><td colSpan={6}>{catalogT('No movements yet.',language)}</td></tr>}</tbody></table></div></section>;
}
