'use client';
import Link from 'next/link';
import { ArrowRight, Calculator, CircleDollarSign, TrendingDown, TrendingUp, WalletCards } from 'lucide-react';
import { useLanguage } from '@/components/language-provider';
import { batchT, storefrontT } from '@/lib/i18n';
type Expense={id:number;expenseDate:string;description:string;category:string;amountIqd:number};
const iqd=(v:number)=>new Intl.NumberFormat('en-IQ').format(Number(v)||0)+' IQD';
const pct=(n:number,d:number)=>d?`${Math.round(n/d*100)}%`:'0%';
export default function ProfitClient({revenue,cost,operating,net,gross,units,knownUnitsSold,unknownUnits,expenseRows,period}:{revenue:number;cost:number;operating:number;net:number;gross:number;units:number;knownUnitsSold:number;unknownUnits:number;expenseRows:Expense[];period:string}){
 const {language}=useLanguage(); const t=(s:string)=>batchT(s,language); const periods=[['today','Today'],['7d','7 days'],['30d','30 days'],['90d','90 days'],['year','Year']];
 return <main className="admin-page"><div className="admin-page-heading"><div><span className="admin-eyebrow"><TrendingUp size={12}/> {t('Finance')}</span><h1>{t('Profit')}</h1><p>{t('Gross and net profit using the historical FIFO purchase cost stored on sold items.')}</p></div><div className="admin-heading-actions"><Link href="/admin/revenue" className="admin-btn admin-btn-ghost">{t('Revenue')} <ArrowRight size={15}/></Link></div></div>
 <div className="admin-filter-bar">{periods.map(([v,l])=><Link key={v} href={`?period=${v}`} className="admin-btn admin-btn-ghost">{t(l)}</Link>)}</div>
 <div className="admin-stats"><div className="admin-stat"><CircleDollarSign size={20}/><strong>{iqd(revenue)}</strong><span>{t('Product revenue')}</span></div><div className="admin-stat"><TrendingDown size={20}/><strong>{iqd(cost)}</strong><span>{t('Known product COGS')}</span></div><div className="admin-stat"><WalletCards size={20}/><strong>{iqd(operating)}</strong><span>{t('Operating expenses')}</span></div><div className="admin-stat"><Calculator size={20}/><strong>{iqd(net)}</strong><span>{t('Net profit')}</span></div></div>
 <div className="admin-grid-2"><section className="admin-card"><div className="admin-card-heading"><h2>{t('Profit bridge')}</h2></div><table className="admin-table"><tbody><tr><td>{t('Product revenue')}</td><td className="num">{iqd(revenue)}</td></tr><tr><td>{t('Less: product COGS')}</td><td className="num">− {iqd(cost)}</td></tr><tr><td><strong>{t('Gross profit')}</strong></td><td className="num"><strong>{iqd(gross)}</strong></td></tr><tr><td>{t('Less: operating expenses')}</td><td className="num">− {iqd(operating)}</td></tr><tr><td><strong>{t('Net profit')}</strong></td><td className="num"><strong>{iqd(net)}</strong></td></tr></tbody></table></section>
 <section className="admin-card"><div className="admin-card-heading"><h2>{t('Margins & cost coverage')}</h2></div><table className="admin-table"><tbody><tr><td>{t('Gross margin')}</td><td className="num">{pct(gross,revenue)}</td></tr><tr><td>{t('Net margin')}</td><td className="num">{pct(net,revenue)}</td></tr><tr><td>{t('Units sold')}</td><td className="num">{units}</td></tr><tr><td>{t('Units with known purchase cost')}</td><td className="num">{knownUnitsSold}</td></tr><tr><td>{t('Units with unknown purchase cost')}</td><td className="num">{unknownUnits}</td></tr></tbody></table></section></div>
 <section className="admin-card"><div className="admin-card-heading"><div><h2>{t('Operating expenses')}</h2><p className="admin-card-subtitle">{t('These expenses are deducted after gross product profit.')}</p></div><Link href="/admin/finance" className="admin-link">{t('Manage expenses')} <ArrowRight size={14}/></Link></div><table className="admin-table"><thead><tr><th>{t('Date')}</th><th>{t('Description')}</th><th>{t('Category')}</th><th className="num">{t('Amount')}</th></tr></thead><tbody>{expenseRows.map(e=><tr key={e.id}><td>{new Date(e.expenseDate).toLocaleDateString('en-GB')}</td><td>{e.description}</td><td>{e.category}</td><td className="num">{iqd(e.amountIqd)}</td></tr>)}{!expenseRows.length&&<tr><td colSpan={4}>{t('No operating expenses in this period.')}</td></tr>}</tbody></table></section><p className="admin-footnote">{t('COGS is calculated from the purchase-cost snapshot saved when inventory was sold. Delivery collections are excluded. If a historical item has no purchase cost, its cost is not invented and the net figure should be treated as a known-cost result.')}</p></main>;
}
