'use client';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, Banknote, CheckCircle2, LoaderCircle, LockKeyhole, MapPin, Phone, ShoppingBag, Tag, Truck, X } from 'lucide-react';
import { useStore } from './store-provider';
import { useLanguage } from './language-provider';
import { storeT } from '@/lib/i18n';

type Zone = { code: string; nameEn: string; nameAr: string; rate: number; minDays: number; maxDays: number };
type Config = { zones: Zone[]; settings: { exchangeRate: number; freeShippingThreshold: number; codFee: number; codEnabled: boolean; checkoutNote: string; supportPhone: string } };
type Coupon = { code: string; discount: number; freeShipping: boolean; description: string };
const iqd = (value: number) => new Intl.NumberFormat('en-IQ', { style: 'currency', currency: 'IQD', maximumFractionDigits: 0 }).format(value);

export function Checkout() {
  const { cart, loaded, refreshCart } = useStore();
  const { language } = useLanguage();
  const t = (label: string) => storeT(label, language);
  const [config, setConfig] = useState<Config | null>(null);
  const [governorate, setGovernorate] = useState('');
  const [couponInput, setCouponInput] = useState('');
  const [coupon, setCoupon] = useState<Coupon | null>(null);
  const [couponError, setCouponError] = useState('');
  const [checkingCoupon, setCheckingCoupon] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState('');
  const [order, setOrder] = useState<{ reference: string; total: number; phone: string; governorate: string; eta: string; shipping: number } | null>(null);
  useEffect(() => { fetch('/api/checkout').then(r => r.json()).then(setConfig).catch(() => setError(language === 'ar' ? 'تعذر تحميل صفحة إتمام الطلب. حدّث الصفحة.' : 'Checkout could not be loaded. Please refresh.')); }, []);
  const rate = config?.settings.exchangeRate ?? 1320;
  const lines = useMemo(() => cart.map(item => ({ ...item, unit: item.salePriceIqd })), [cart]);
  const subtotal = lines.reduce((sum, item) => sum + item.unit * item.quantity, 0);
  const zone = config?.zones.find(item => item.code === governorate);
  const freeShipping = (config ? subtotal >= config.settings.freeShippingThreshold : false) || Boolean(coupon?.freeShipping);
  const shipping = zone ? (freeShipping ? 0 : zone.rate) : 0;
  const discount = coupon ? Math.min(coupon.discount, subtotal) : 0;
  const codFee = config?.settings.codFee ?? 0;
  const total = Math.max(0, subtotal - discount) + shipping + codFee;
  async function applyCoupon() {
    setCheckingCoupon(true); setCouponError('');
    try { const response = await fetch('/api/checkout', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ code: couponInput, subtotal }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setCoupon(data); }
    catch (err) { setCoupon(null); setCouponError(err instanceof Error ? err.message : (language === 'ar' ? 'تعذر تطبيق القسيمة.' : 'Coupon could not be applied.')); }
    finally { setCheckingCoupon(false); }
  }
  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (submitting) return; setError(''); setSubmitting(true);
    const data = Object.fromEntries(new FormData(event.currentTarget));
    try { const response = await fetch('/api/orders', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...data, coupon: coupon?.code ?? '' }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setOrder(result.order); await refreshCart(); window.scrollTo({ top: 0, behavior: 'smooth' }); }
    catch (err) { setError(err instanceof Error ? err.message : (language === 'ar' ? 'تحقق من الاتصال وحاول مرة أخرى.' : 'Please check your connection and try again.')); }
    finally { setSubmitting(false); }
  }
  if (order) return <main className="checkout-page"><div className="order-success"><CheckCircle2 size={54} strokeWidth={1.2} /><span className="eyebrow">Shukran · شكراً</span><h1>{language === 'ar' ? 'طلبك في طريقه إليك.' : 'Your order is on its way.'}</h1><p>{language === 'ar' ? <>سنتصل على <strong>{order.phone}</strong> لتأكيد الطلب قبل الشحن.<br />التوصيل إلى {order.governorate} يستغرق عادة {order.eta}.</> : <>We’ll call <strong>{order.phone}</strong> to confirm before dispatch.<br />Delivery to {order.governorate} usually takes {order.eta}.</>}</p><div className="order-reference">{language === 'ar' ? 'رقم الطلب' : 'Order'} {order.reference}</div><p>{language === 'ar' ? <>ادفع <strong>{iqd(order.total)}</strong> نقداً عند وصول طلبك.<br />{order.shipping === 0 ? 'التوصيل علينا.' : `يشمل ${iqd(order.shipping)} أجور التوصيل.`}</> : <>Pay <strong>{iqd(order.total)}</strong> in cash when your order arrives.<br />{order.shipping === 0 ? 'Delivery is on us.' : `Includes ${iqd(order.shipping)} delivery.`}</>}</p><Link className="button button-orange" href="/">{language === 'ar' ? 'متابعة التصفح' : 'Keep exploring'} <ArrowRight size={17} /></Link></div></main>;
  if (!loaded || !config) return <main className="checkout-page"><div className="empty-cart"><LoaderCircle className="spin" size={32} /><h3>{language === 'ar' ? 'جارٍ تجهيز سلتك…' : 'Getting your bag ready…'}</h3>{error && <p className="form-error">{error}</p>}</div></main>;
  if (!cart.length) return <main className="checkout-page"><div className="empty-cart"><ShoppingBag size={48} strokeWidth={1.1} /><h3>{language === 'ar' ? 'مغامرتك القادمة تبدأ من هنا.' : 'Your next adventure starts here.'}</h3><p>{language === 'ar' ? 'سلتك فارغة. دعنا نجد لك اختياراً مناسباً.' : 'Your bag is empty. Let’s find you a companion.'}</p><Link href="/collection/bestsellers" className="button button-orange">{language === 'ar' ? 'استعرض الأكثر مبيعاً' : 'Explore bestsellers'} <ArrowRight size={17} /></Link></div></main>;
  return <main className="checkout-page"><Link className="text-link" href="/products/category/all"><ArrowLeft size={15} /> {language === 'ar' ? 'العودة للتصفح' : 'Back to exploring'}</Link><div className="checkout-heading"><h1>{language === 'ar' ? 'الخطوة الأخيرة.' : 'The last little step.'}</h1><span><LockKeyhole size={14} /> {language === 'ar' ? 'التوصيل إلى جميع أنحاء العراق · الدفع عند الاستلام' : 'Delivery across Iraq · Cash on delivery'}</span></div><div className="checkout-layout"><form className="checkout-form" onSubmit={submit}><div className="checkout-demo-note"><Truck size={15} style={{ display: 'inline', verticalAlign: 'middle', marginRight: 6 }} />{config.settings.checkoutNote}</div>
    <h2>1. {language === 'ar' ? 'من سيستلم الطلب؟' : 'Who’s receiving it?'}</h2><div className="form-grid"><div className="form-field full"><label htmlFor="name">Full name · الاسم الكامل</label><input id="name" name="name" autoComplete="name" maxLength={100} required /></div><div className="form-field"><label htmlFor="phone">Mobile number · رقم الهاتف</label><input id="phone" name="phone" type="tel" inputMode="numeric" autoComplete="tel" placeholder="07XX XXX XXXX" maxLength={20} required /></div><div className="form-field"><label htmlFor="altPhone">{language === 'ar' ? 'رقم بديل (اختياري)' : 'Alternative number (optional)'}</label><input id="altPhone" name="altPhone" type="tel" inputMode="numeric" placeholder="07XX XXX XXXX" maxLength={20} /></div><div className="form-field full"><label htmlFor="email">{language === 'ar' ? 'البريد الإلكتروني (اختياري، للإيصال)' : 'Email (optional, for your receipt)'}</label><input id="email" name="email" type="email" autoComplete="email" maxLength={254} /></div></div>
    <h2>2. {t('Where to?')}</h2><div className="form-grid"><div className="form-field full"><label htmlFor="governorate">{language === 'ar' ? 'المحافظة' : 'Governorate'} · المحافظة</label><select id="governorate" name="governorate" required value={governorate} onChange={event => setGovernorate(event.target.value)}><option value="">{t('Choose your governorate')}</option>{config.zones.map(item => <option key={item.code} value={item.code}>{item.nameEn} · {item.nameAr}</option>)}</select>{zone && <small className="field-hint"><MapPin size={12} /> {language === 'ar' ? 'التوصيل' : 'Delivery'} {freeShipping ? t('Free') : iqd(zone.rate)} · {zone.minDays}–{zone.maxDays} {language === 'ar' ? 'يوم عمل' : 'business days'}</small>}</div><div className="form-field full"><label htmlFor="city">{t('City / district')} · المدينة أو القضاء</label><input id="city" name="city" autoComplete="address-level2" placeholder={language === 'ar' ? 'مثال: الكرادة، المنصور، العشار' : 'e.g. Karrada, Mansour, Al-Ashar'} maxLength={120} required /></div><div className="form-field full"><label htmlFor="address">{t('Detailed address')} · العنوان بالتفصيل</label><input id="address" name="address" autoComplete="street-address" placeholder={language === 'ar' ? 'المنطقة، الشارع، رقم المنزل أو البناية' : 'Neighbourhood, street, house/building number'} maxLength={300} required /></div><div className="form-field full"><label htmlFor="landmark">{t('Nearest landmark (optional)')} · أقرب نقطة دالة</label><input id="landmark" name="landmark" placeholder={language === 'ar' ? 'مثال: قرب بوابة متنزه الزوراء' : 'e.g. next to Al-Zawraa park gate'} maxLength={200} /></div><div className="form-field full"><label htmlFor="note">{t('Delivery notes (optional)')}</label><textarea id="note" name="note" rows={3} maxLength={500} placeholder={language === 'ar' ? 'وقت التوصيل المفضل، تغليف هدية…' : 'Preferred delivery time, gift wrapping…'} /></div></div>
    <h2>3. {t('Payment')}</h2><label className="shipping-option"><input type="radio" name="payment" value="cod" defaultChecked readOnly /><div><strong><Banknote size={15} style={{ display: 'inline', verticalAlign: 'middle', marginRight: 6 }} />Cash on delivery · الدفع عند الاستلام</strong><small>{language === 'ar' ? 'ادفع للمندوب بالدينار العراقي عند وصول طلبك.' : 'Pay the courier in Iraqi dinars when your order arrives.'}{codFee ? (language === 'ar' ? `تُضاف رسوم دفع ${iqd(codFee)}.` : `A ${iqd(codFee)} handling fee applies.`) : ''}</small></div><strong>{iqd(total)}</strong></label>
    {error && <p className="form-error" role="alert">{error}</p>}<button type="submit" className="button button-orange button-full" disabled={submitting || !governorate}>{submitting ? <><LoaderCircle size={17} className="spin" /> {t('Placing your order…')}</> : <>{t('Place order')} · {iqd(total)} <ArrowRight size={17} /></>}</button><div className="secure-note">{t('By continuing, you agree to our')} <Link href="/info/terms">{language === 'ar' ? 'الشروط والأحكام.' : 'terms & conditions.'}</Link> {t('Questions?')} <a href={`tel:${config.settings.supportPhone}`}><Phone size={11} /> {config.settings.supportPhone}</a></div></form>
    <aside className="checkout-summary"><h2>{t('Your good company')}</h2><div className="checkout-summary-items">{lines.map(item => <div className="checkout-summary-item" key={item.id}><div className="checkout-summary-image"><img src={item.image} alt={`${item.name} in ${item.color}`} /><span>{item.quantity}</span></div><div><h3>{item.name}</h3><p>{item.color}</p></div><span>{iqd(item.unit * item.quantity)}</span></div>)}</div>
      <div className="coupon-row">{coupon ? <div className="coupon-applied"><Tag size={14} /> <strong>{coupon.code}</strong> · {coupon.description}{coupon.freeShipping ? ` · ${t('Free')}` : ''}<button type="button" aria-label={t('Remove coupon')} onClick={() => { setCoupon(null); setCouponInput(''); }}><X size={14} /></button></div> : <><input aria-label="Coupon code" placeholder={t('Coupon code')} value={couponInput} onChange={event => setCouponInput(event.target.value.toUpperCase())} /><button type="button" className="button button-outline" disabled={!couponInput.trim() || checkingCoupon} onClick={applyCoupon}>{checkingCoupon ? <LoaderCircle size={14} className="spin" /> : t('Apply')}</button></>}</div>{couponError && <p className="form-error">{couponError}</p>}
      <div className="checkout-total-row"><span>{t('Subtotal')}</span><span>{iqd(subtotal)}</span></div>{discount > 0 && <div className="checkout-total-row discount"><span>{language === 'ar' ? 'الخصم' : 'Discount'}</span><span>− {iqd(discount)}</span></div>}<div className="checkout-total-row"><span>{t('Delivery')} {zone ? `· ${language === 'ar' ? zone.nameAr : zone.nameEn}` : ''}</span><span>{!zone ? t('Choose your governorate') : shipping === 0 ? t('Free') : iqd(shipping)}</span></div>{codFee > 0 && <div className="checkout-total-row"><span>{t('Cash handling')}</span><span>{iqd(codFee)}</span></div>}<div className="checkout-total-row checkout-grand-total"><span>{t('Total')} <small style={{ fontSize: 10, color: '#939b86' }}>IQD</small></span><strong>{iqd(total)}</strong></div>{!freeShipping && config.settings.freeShippingThreshold > subtotal && <p className="checkout-summary-note">{language === 'ar' ? <>أضف {iqd(config.settings.freeShippingThreshold - subtotal)} للحصول على توصيل مجاني إلى أي مكان في العراق.</> : <>Add {iqd(config.settings.freeShippingThreshold - subtotal)} more for free delivery anywhere in Iraq.</>}</p>}<p className="checkout-summary-note">{t('Sale prices are fixed in IQD. USD is used only for purchase cost and reference.')}</p></aside></div></main>;
}
