const { chromium, expect } = require('@playwright/test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const base = process.env.TEST_BASE_URL || 'http://localhost:3000';

(async () => {
  fs.mkdirSync('artifacts', { recursive: true });
  const browser = await chromium.launch({ headless: true, args: ['--no-sandbox'] });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(base, { waitUntil: 'networkidle' });
  await page.evaluate(() => document.fonts.ready);
  await page.screenshot({ path: 'artifacts/final-desktop.png' });
  await page.getByRole('button', { name: 'Got it', exact: true }).click();
  await page.getByRole('button', { name: 'Show slide 2: Shop bestsellers', exact: true }).click();
  await expect(page.locator('.hero-slide-active')).toContainText('Carry smart.');
  await page.getByRole('button', { name: 'Show slide 1: Shop tech', exact: true }).click();
  await page.locator('.desktop-navigation a').filter({ hasText: 'Bags & Luggage' }).hover();
  await expect(page.locator('.mega-menu')).toBeVisible();
  await page.locator('.mega-menu').getByRole('link', { name: 'Backpacks', exact: true }).click();
  await expect(page).toHaveURL(/\/products\/category\/backpacks$/);
  await page.getByRole('button', { name: 'Filter', exact: true }).click();
  const price = page.getByRole('slider', { name: 'Maximum product price' });
  await price.focus(); await price.press('Home');
  await expect(page.getByRole('heading', { name: 'A fresh start?' })).toBeVisible();
  await page.getByRole('button', { name: 'Clear filters', exact: true }).click();
  await page.getByLabel('Sort by', { exact: true }).selectOption('price-asc');
  const prices = await page.locator('.catalog-grid .product-title-row>span').allTextContents();
  const numericPrices = prices.map(value => Number(value.replace(/[^0-9.]/g, '')));
  assert.deepEqual(numericPrices, [...numericPrices].sort((a, b) => a - b));
  await page.getByRole('button', { name: 'Search products', exact: true }).click();
  await page.getByRole('textbox', { name: 'Search products', exact: true }).fill('tech kit');
  await expect(page.locator('.search-label')).toContainText('1 result');
  await page.locator('.search-products').getByRole('link', { name: 'Tech Kit', exact: true }).click();
  await expect(page).toHaveURL(/\/products\/tech-kit$/);
  await page.getByRole('button', { name: 'Choose Black', exact: true }).click();
  await expect(page.locator('.product-main-image>img')).toHaveAttribute('src', /tech-kit-black\.jpg$/);
  await page.getByRole('button', { name: 'Show photo 2', exact: true }).click();
  await expect(page.locator('.product-main-image>img')).toHaveAttribute('src', /black-detail\.jpg$/);
  await page.getByRole('button', { name: 'Zoom product image', exact: true }).click();
  await expect(page.getByRole('dialog', { name: 'Tech Kit image', exact: true })).toBeVisible();
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: 'Increase quantity', exact: true }).click();
  await page.getByRole('button', { name: /^Add to bag/ }).click();
  const bag = page.getByRole('dialog', { name: 'Your shopping bag', exact: true });
  await expect(bag).toBeVisible();
  await expect(bag.locator('.quantity-control>span')).toHaveText('2');
  await bag.getByRole('button', { name: 'Decrease Tech Kit quantity', exact: true }).click();
  await expect(bag.locator('.quantity-control>span')).toHaveText('1');
  await page.keyboard.press('Escape');
  await page.reload({ waitUntil: 'networkidle' });
  await expect(page.locator('.bag-count')).toHaveText('1');
  await page.getByRole('button', { name: 'Open shopping bag, 1 items', exact: true }).click();
  await bag.getByRole('button', { name: 'Remove', exact: true }).click();
  await expect(bag.getByRole('heading', { name: 'Good things are waiting.' })).toBeVisible();
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: /^Add to bag/ }).click();
  await expect(bag).toBeVisible();
  await bag.getByRole('link', { name: 'Checkout', exact: true }).click();
  await expect(page).toHaveURL(/\/checkout$/);
  await page.getByLabel('Full name · الاسم الكامل').fill('Ali Hassan');
  await page.getByLabel('Mobile number · رقم الهاتف').fill('0770 123 4567');
  await page.getByLabel('Governorate · المحافظة').selectOption('baghdad');
  await page.getByLabel('City / district · المدينة أو القضاء').fill('Karrada');
  await page.getByLabel('Detailed address · العنوان بالتفصيل').fill('Street 62, building 14, flat 3');
  await expect(page.locator('.checkout-grand-total')).toContainText('IQD');
  const invalidPhone = await page.request.post(base + '/api/orders', { data: { name: 'Bad Phone', phone: '12345', governorate: 'baghdad', city: 'X', address: 'Some street 1' } });
  assert.equal(invalidPhone.status(), 400);
  await page.getByRole('button', { name: /^Place order/ }).click();
  await expect(page.getByRole('heading', { name: 'Your order is on its way.', exact: true })).toBeVisible();
  const reference = await page.locator('.order-reference').textContent();
  assert.match(reference, /BR-[A-F0-9]{6}/);
  const cartResponse = await page.request.get(base + '/api/cart');
  assert.equal((await cartResponse.json()).items.length, 0);
  await page.screenshot({ path: 'artifacts/checkout-success.png' });
  console.log('PASS: desktop navigation, filters, sorting, live search, color images, zoom, persistent cart, quantities, removal, Iraq COD checkout', reference);

  await page.goto(base, { waitUntil: 'networkidle' });
  await page.getByLabel('Your email address', { exact: true }).fill('demo-newsletter@example.com');
  await page.getByRole('button', { name: 'Subscribe to the Bellroy newsletter', exact: true }).click();
  await expect(page.locator('.newsletter-success')).toContainText('You’re in good company.');
  const duplicate = await page.request.post(base + '/api/newsletter', { data: { email: 'demo-newsletter@example.com' } });
  assert.equal(duplicate.status(), 200);
  await page.goto(base + '/info/contact', { waitUntil: 'networkidle' });
  await page.getByLabel('Your name', { exact: true }).fill('Demo Shopper');
  await page.getByLabel('Email address', { exact: true }).fill('demo-contact@example.com');
  await page.getByLabel('How can we help?', { exact: true }).selectOption('My demo order');
  await page.getByLabel('Your message', { exact: true }).fill('This is an automated demonstration support message.');
  await page.getByRole('button', { name: 'Send your message', exact: true }).click();
  await expect(page.locator('.contact-success')).toContainText('HELP-');
  await page.getByRole('button', { name: 'Choose your country and currency', exact: true }).click();
  await page.getByLabel('Country / region', { exact: true }).selectOption('United States');
  await page.getByRole('button', { name: 'Save preferences', exact: true }).click();
  await page.goto(base + '/products/tech-kit', { waitUntil: 'networkidle' });
  await expect(page.locator('.product-price')).toContainText('USD');
  await page.getByRole('button', { name: 'Choose your country and currency', exact: true }).click();
  await page.getByLabel('Country / region', { exact: true }).selectOption('Iraq');
  await page.getByRole('button', { name: 'Save preferences', exact: true }).click();
  await page.getByRole('button', { name: 'Sign up for new releases', exact: true }).filter({ visible: true }).click();
  const popup = page.getByRole('dialog', { name: 'New releases and subscriber exclusives', exact: true });
  await expect(popup).toBeVisible();
  await expect(popup.getByLabel('Your email address')).toBeVisible();
  await page.keyboard.press('Escape');
  console.log('PASS: newsletter persistence, duplicate subscriptions, contact form, region preferences, newsletter dialog');

  const mobileContext = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, reducedMotion: 'reduce' });
  const mobile = await mobileContext.newPage();
  mobile.on('pageerror', error => errors.push(error.message));
  await mobile.goto(base, { waitUntil: 'networkidle' });
  await mobile.evaluate(() => document.fonts.ready);
  await mobile.screenshot({ path: 'artifacts/final-mobile.png' });
  assert.equal(await mobile.evaluate(() => document.documentElement.scrollWidth), 390);
  const mobileCart = await mobile.request.get(base + '/api/cart');
  assert.equal((await mobileCart.json()).items.length, 0);
  await mobile.getByRole('button', { name: 'Got it', exact: true }).click();
  await mobile.getByRole('button', { name: 'Open menu', exact: true }).click();
  const menu = mobile.getByRole('dialog', { name: 'Navigation menu', exact: true });
  await menu.getByRole('button', { name: 'Bags & Luggage', exact: true }).click();
  await menu.getByRole('link', { name: 'Backpacks', exact: true }).click();
  await expect(mobile).toHaveURL(/\/products\/category\/backpacks$/);
  await expect(menu).not.toBeVisible();
  assert.equal(await mobile.evaluate(() => document.documentElement.scrollWidth), 390);
  await mobile.locator('.catalog-grid').getByRole('link', { name: 'Transit Workpack', exact: true }).click();
  await mobile.getByRole('button', { name: 'Choose Olive', exact: true }).click();
  await expect(mobile.locator('.product-main-image>img')).toHaveAttribute('src', /transit-workpack-olive\.jpg$/);
  await expect(mobile.getByRole('button', { name: 'Choose Stone', exact: true })).toHaveClass(/swatch-sold-out/);
  await mobile.getByRole('button', { name: /^Add to bag/ }).click();
  const mobileBag = mobile.getByRole('dialog', { name: 'Your shopping bag', exact: true });
  await expect(mobileBag).toContainText('Olive');
  await mobile.screenshot({ path: 'artifacts/mobile-cart.png' });
  await mobileBag.getByRole('button', { name: 'Remove', exact: true }).click();
  await expect(mobileBag.getByRole('heading', { name: 'Good things are waiting.' })).toBeVisible();
  await mobile.keyboard.press('Escape');
  console.log('PASS: mobile layout, navigation drawer, isolated shopping session, variant selection, shopping bag');

  for (const path of ['/products/category/all', '/products/lite-travel-pack', '/products/lite-sling', '/collection/travel', '/collection/venture', '/search?q=wallet', '/info/shipping', '/info/our-materials', '/info/warranty', '/info/stores', '/info/journal', '/info/privacy']) {
    const response = await page.request.get(base + path); assert.equal(response.status(), 200, path);
  }
  const invalidProduct = await page.request.get(base + '/products/does-not-exist'); assert.equal(invalidProduct.status(), 404);
  const invalidEmail = await page.request.post(base + '/api/newsletter', { data: { email: 'not-an-email' } }); assert.equal(invalidEmail.status(), 400);
  const invalidCart = await page.request.post(base + '/api/cart', { data: { productId: 'not-a-product', color: 'Black', quantity: 1 } }); assert.equal(invalidCart.status(), 400);
  const catalog = await (await page.request.get(base + '/api/products')).json();
  for (const product of catalog.products) {
    for (const color of product.colors) { assert.ok(color.images.length >= 2, `${product.id}/${color.name} images`); assert.ok(Number.isInteger(color.stock), 'stock'); for (const asset of color.images) if (asset.startsWith('/images/')) assert.ok(fs.existsSync('public' + asset), asset); }
  }
  console.log('PASS: route coverage, 404s, server-side validation, all catalog images');
  // Same photo position across colors
  await page.goto(base + '/products/transit-workpack?color=Bronze', { waitUntil: 'networkidle' });
  await page.getByRole('button', { name: 'Show photo 2', exact: true }).click();
  await expect(page.locator('.product-main-image>img')).toHaveAttribute('src', /transit-workpack-bronze-detail\.jpg$/);
  await page.getByRole('button', { name: 'Choose Nightsky', exact: true }).click();
  await expect(page.locator('.product-main-image>img')).toHaveAttribute('src', /transit-workpack-nightsky-detail\.jpg$/);
  await expect(page.locator('.gallery-counter')).toHaveText('2 / 2');
  await page.getByRole('button', { name: 'Choose Stone', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Sold out in this color' })).toBeDisabled();
  const soldOutAdd = await page.request.post(base + '/api/cart', { data: { variantId: (await (await page.request.get(base + '/api/products?q=transit workpack')).json()).products[0].colors.find(c => c.name === 'Stone').id, quantity: 1 } });
  assert.equal(soldOutAdd.status(), 409);
  console.log('PASS: photo position persists across colors, sold-out color blocked');

  // Admin: auth, stock edit, per-color photos, main photo, new product
  const denied = await page.request.get(base + '/api/admin/products'); assert.equal(denied.status(), 401);
  await page.goto(base + '/admin/products', { waitUntil: 'networkidle' });
  await expect(page).toHaveURL(/\/admin\/login$/);
  await page.getByLabel('Admin password').fill('wrong-password');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await expect(page.locator('.admin-error')).toBeVisible();
  await page.getByLabel('Admin password').fill(process.env.ADMIN_PASSWORD || 'bellroy-admin');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await expect(page).toHaveURL(/\/admin$/);
  await page.screenshot({ path: 'artifacts/admin-dashboard.png', fullPage: true });
  await page.goto(base + '/admin/products/tech-kit', { waitUntil: 'networkidle' });
  await page.getByRole('tab', { name: /Saltbush/ }).click();
  await page.getByLabel('Stock quantity').fill('2');
  const beforeUpload = await page.locator('.admin-photo-grid li').count();
  await page.locator('input[type=file]').setInputFiles({ name: 'saltbush-extra.png', mimeType: 'image/png', buffer: fs.readFileSync('public/images/tech-kit-saltbush.jpg') });
  await expect(page.locator('.admin-photo-grid li')).toHaveCount(beforeUpload + 1);
  await page.locator('.admin-photo-grid li').nth(beforeUpload).getByRole('button', { name: 'Set as main photo' }).click();
  await expect(page.locator('.admin-photo-grid li').nth(beforeUpload)).toHaveClass(/primary/);
  await page.getByRole('button', { name: 'Save changes' }).first().click();
  await expect(page.locator('.admin-alert.success')).toContainText('Saved');
  await page.screenshot({ path: 'artifacts/admin-editor.png', fullPage: true });
  const saved = (await (await page.request.get(base + '/api/admin/products/tech-kit')).json()).product;
  const saltbush = saved.colors.find(c => c.name === 'Saltbush');
  assert.equal(saltbush.stock, 2); assert.equal(saltbush.images.length, beforeUpload + 1); assert.match(saltbush.images[saltbush.primaryIndex], /^\/api\/media\/\d+$/);
  const mediaResponse = await page.request.get(base + saltbush.images[saltbush.primaryIndex]); assert.equal(mediaResponse.status(), 200); assert.equal(mediaResponse.headers()['content-type'], 'image/webp');
  await page.goto(base + '/products/tech-kit?color=Saltbush', { waitUntil: 'networkidle' });
  await expect(page.locator('.stock-note')).toHaveText('Only 2 left');
  await expect(page.locator('.product-main-image>img')).toHaveAttribute('src', /\/api\/media\/\d+$/);
  await page.goto(base + '/admin/products/new', { waitUntil: 'networkidle' });
  await page.getByPlaceholder('Transit Workpack').fill('Smoke Test Tote');
  await page.getByPlaceholder('199').fill('120');
  await page.getByLabel('Category').selectOption('tote-bags');
  await page.getByLabel('Image URL').fill('/images/tokyo-totepack-navy.jpg'); await page.getByRole('button', { name: 'Add', exact: true }).click();
  await page.getByLabel('Image URL').fill('/images/tokyo-totepack-navy-detail.jpg'); await page.getByRole('button', { name: 'Add', exact: true }).click();
  await page.getByLabel('Stock quantity').fill('7');
  await page.getByRole('button', { name: 'Create product' }).first().click();
  await expect(page).toHaveURL(/\/admin\/products\/smoke-test-tote$/);
  const created = await page.request.get(base + '/products/smoke-test-tote'); assert.equal(created.status(), 200);
  const removed = await page.request.delete(base + '/api/admin/products/smoke-test-tote'); assert.equal(removed.status(), 200);
  assert.equal((await page.request.get(base + '/products/smoke-test-tote')).status(), 404);
  // Admin modules: orders pipeline, inventory, coupons, shipping, banners, content, settings
  const ordersPage = await page.goto(base + '/admin/orders', { waitUntil: 'networkidle' });
  assert.equal(ordersPage.status(), 200);
  await page.locator('.admin-orders-table').getByRole('link', { name: reference.replace('Order ', '').trim(), exact: true }).first().click();
  await expect(page.getByRole('heading', { name: /^Order BR-/ })).toBeVisible();
  const orderId = page.url().split('/').pop();
  const before = (await (await page.request.get(base + '/api/admin/products/tech-kit')).json()).product.colors.find(c => c.name === 'Black').stock;
  await page.getByRole('button', { name: 'Mark as confirmed' }).click();
  await expect(page.locator('.admin-steps li.current')).toContainText('Confirmed');
  await page.getByRole('button', { name: 'Mark as processing' }).click();
  await expect(page.locator('.admin-steps li.current')).toContainText('Processing');
  await page.getByPlaceholder('e.g. Al-Barid, Sandoog, in-house').fill('In-house courier');
  await page.getByRole('button', { name: 'Mark as shipped' }).click();
  await expect(page.locator('.admin-steps li.current')).toContainText('Shipped');
  await page.getByRole('button', { name: 'Mark as delivered' }).click();
  await expect(page.locator('.admin-steps li.current')).toContainText('Delivered');
  await expect(page.getByRole('button', { name: 'Mark as returned' })).toBeVisible();
  const delivered = await (await page.request.get(base + `/api/admin/orders/${orderId}`)).json();
  assert.equal(delivered.order.status, 'delivered'); assert.equal(delivered.order.paymentStatus, 'paid'); assert.ok(delivered.events.length >= 4);
  const illegal = await page.request.patch(base + `/api/admin/orders/${orderId}`, { data: { status: 'pending' } }); assert.equal(illegal.status(), 400);
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: 'Mark as returned' }).click();
  await expect(page.locator('.admin-alert.info')).toContainText('returned');
  const after = (await (await page.request.get(base + '/api/admin/products/tech-kit')).json()).product.colors.find(c => c.name === 'Black').stock;
  assert.equal(after, before + 1, 'stock restored on return');
  await page.screenshot({ path: 'artifacts/admin-order.png', fullPage: true });
  // inventory
  await page.goto(base + '/admin/inventory', { waitUntil: 'networkidle' });
  const navyInput = page.getByLabel('Set stock for Tech Kit Navy');
  await navyInput.fill('40');
  await navyInput.locator('xpath=..').getByRole('button', { name: 'Set', exact: true }).click();
  await expect(page.locator('.admin-alert.success')).toContainText('40 in stock');
  await page.screenshot({ path: 'artifacts/admin-inventory.png', fullPage: true });
  // coupons
  const couponCreate = await page.request.post(base + '/api/admin/coupons', { data: { code: 'SMOKE10', type: 'percent', value: 10, minSubtotal: 0, active: true } }); assert.equal(couponCreate.status(), 201);
  const couponId = (await couponCreate.json()).item.id;
  const couponCheck = await page.request.post(base + '/api/checkout', { data: { code: 'smoke10', subtotal: 100000 } }); assert.equal(couponCheck.status(), 200); assert.equal((await couponCheck.json()).discount, 10000);
  await page.goto(base + '/admin/coupons', { waitUntil: 'networkidle' }); await expect(page.locator('.admin-code', { hasText: 'SMOKE10' })).toBeVisible();
  await page.request.delete(base + `/api/admin/coupons/${couponId}`);
  const couponGone = await page.request.post(base + '/api/checkout', { data: { code: 'SMOKE10', subtotal: 100000 } }); assert.equal(couponGone.status(), 400);
  // shipping zones
  await page.goto(base + '/admin/shipping', { waitUntil: 'networkidle' });
  const basraRate = page.getByLabel('Basra rate');
  await basraRate.fill('9000');
  await basraRate.locator('xpath=ancestor::tr').getByRole('button', { name: 'Save' }).click();
  await expect(page.locator('.admin-alert.success')).toContainText('Basra updated');
  const zones = (await (await page.request.get(base + '/api/checkout')).json()).zones; assert.equal(zones.find(z => z.code === 'basra').rate, 9000); assert.equal(zones.length, 18);
  // banners
  await page.goto(base + '/admin/banners', { waitUntil: 'networkidle' });
  await page.locator('section.admin-card', { hasText: 'Homepage hero slides' }).getByRole('button', { name: 'Add' }).click();
  await page.getByPlaceholder('Carry smart.\nMove free.').fill('Smoke test banner');
  await page.getByPlaceholder('/collection/bestsellers').fill('/collection/travel');
  await page.getByLabel('Desktop image URL').fill('/images/hero-carry.jpg');
  await page.getByRole('button', { name: 'Save banner' }).click();
  await expect(page.locator('.admin-banner-card', { hasText: 'Smoke test banner' })).toBeVisible();
  await page.goto(base, { waitUntil: 'networkidle' });
  await expect(page.locator('.hero-dots button')).toHaveCount(4);
  const bannersList = (await (await page.request.get(base + '/api/admin/banners')).json()).items; const smokeBanner = bannersList.find(b => b.title === 'Smoke test banner'); await page.request.delete(base + `/api/admin/banners/${smokeBanner.id}`);
  // content + settings
  const contentSave = await page.request.put(base + '/api/admin/content/shipping', { data: { eyebrow: 'Delivery in Iraq', title: 'Delivered to your door, anywhere in Iraq.', subtitle: 'Cash on delivery to all 18 governorates.', sections: [], faqs: [{ question: 'Where do you deliver?', answer: 'Everywhere in Iraq.' }], published: true } }); assert.equal(contentSave.status(), 200);
  await page.goto(base + '/info/shipping', { waitUntil: 'networkidle' }); await expect(page.getByRole('heading', { level: 1 })).toContainText('anywhere in Iraq');
  const settingsSave = await page.request.put(base + '/api/admin/settings', { data: { announcement: 'Smoke announcement · free delivery over 150,000 IQD' } }); assert.equal(settingsSave.status(), 200);
  await page.goto(base, { waitUntil: 'networkidle' }); await expect(page.locator('.shipping-link')).toContainText('Smoke announcement');
  await page.request.put(base + '/api/admin/settings', { data: { announcement: 'Free delivery across Iraq on orders over 150,000 IQD · Cash on delivery' } });
  for (const path of ['/admin', '/admin/customers', '/admin/messages', '/admin/content', '/admin/settings', `/admin/customers?q=0770`]) { const response = await page.request.get(base + path); assert.equal(response.status(), 200, path); }
  await page.goto(base + '/admin', { waitUntil: 'networkidle' }); await page.screenshot({ path: 'artifacts/admin-dashboard.png', fullPage: true });
  console.log('PASS: order pipeline with stock restore, inventory adjustments, coupons, Iraq delivery zones, banners, content, settings');
  await page.request.delete(base + '/api/admin/login');
  console.log('PASS: admin authentication, per-color stock, photo upload, main photo, storefront sync, product create/delete');

  await page.goto(base, { waitUntil: 'networkidle' });
  await page.getByRole('button', { name: 'Play Cinch Cinch revolution', exact: true }).click();
  await expect(page.getByRole('dialog', { name: 'Watch Cinch Cinch revolution', exact: true }).locator('iframe')).toHaveAttribute('src', /youtube-nocookie\.com\/embed\/GNDqj75YIkE/);
  await page.keyboard.press('Escape');
  for (let y = 0; y < 10000; y += 650) { await page.evaluate(y => window.scrollTo(0, y), y); await page.waitForTimeout(100); }
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: 'artifacts/final-full.png', fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth), 1440);
  const broken = await page.evaluate(() => [...document.images].filter(image => image.complete && !image.naturalWidth).map(image => image.src));
  assert.deepEqual(broken, []);
  assert.deepEqual(errors, []);
  console.log('PASS: video dialog, full-page rendering, no broken images, no browser exceptions');
  console.log('ALL SMOKE TESTS PASSED');
  await browser.close();
})().catch(error => { console.error(error); process.exit(1); });
